open Util
open Tbwd
open Dim
open Modal
open Core
open Reporter
open Tctx
open Term
module StringSet = Set.Make (String)

(* Track the used variable names, to generate fresh ones for bound variables if needed. *)

(* We store a parametrized list of cubes of variable names like a context, along with a mapping of field names to local variable names bound textually to that field of the variable.  Unlike in terms, every variable stored here has a name: anonymous variables are assigned an autogenerated name when they are added. *)
type 'b ctx =
  | Emp : 'mode emp ctx
  | Snoc :
      'b ctx * ('n, string) gvariables * (string, string) Abwd.t
      -> ('b, ('modality, 'n) dim_entry) snoc ctx
  | Lock : 'b ctx -> ('b, 'modality lock_entry) snoc ctx

(* We also store a set of which variables already exist, so that we can be sure of creating a new unused one. *)
type 'b t = { ctx : 'b ctx; used : StringSet.t }
type wrapped = Wrap : 'n t -> wrapped

let empty : type mode. mode emp t = { ctx = Emp; used = StringSet.empty }

let rec remove_ctx : type a x n b. b ctx -> (a, x, n, b) insert -> a ctx =
 fun ctx i ->
  match (ctx, i) with
  | Snoc (ctx, vars, flds), Later i -> Snoc (remove_ctx ctx i, vars, flds)
  | Snoc (ctx, _, _), Now -> ctx
  | Emp, _ -> .
  | Lock _, _ -> .

let remove : type a x n b. b t -> (a, x, n, b) insert -> a t =
 fun { ctx; used } i -> { ctx = remove_ctx ctx i; used }

(* TODO(about-merge): about defined `extract_ctx`/`permute_ctx`/`permute` here (Tbwd-permutation of the name context, used by match-branch display in unparse.ml).  They are built on Tbwd.insert/Tbwd.permute over plain type-lists, which don't fit modal's dim_entry/lock_entry-indexed context.  Match display is deferred, so these are omitted for now. *)

(* let rec bsplit_ctx : type a b ab x y z. ab ctx -> (x, b, y, a, z, ab) Tctx.bcomp -> a ctx =
    fun ctx ab ->
     match ab with
     | Zero -> ctx
     | Suc (Dim _, ab) ->
         let (Snoc (ctx, _, _)) = bsplit_ctx ctx ab in
         ctx
     | Suc (Lock _, ab) ->
         let (Lock ctx) = bsplit_ctx ctx ab in
         ctx
     | Suc (Proj _, _) -> fatal (Anomaly "Names.bsplit_ctx on Proj") *)

let rec split_ctx : type a b ab x y z. ab ctx -> (x, b, y, a, z, ab) Tctx.comp -> a ctx =
 fun ctx ab ->
  match (ctx, ab) with
  | _, Zero -> ctx
  | Emp, Suc (_, Proj _) -> fatal (Anomaly "Names.split_ctx on Proj")
  | Snoc (ctx, _, _), Suc (ab, Dim _) -> split_ctx ctx ab
  | Lock ctx, Suc (ab, Lock _) -> split_ctx ctx ab

let split : type a b ab x y z. ab t -> (x, b, y, a, z, ab) Tctx.comp -> a t =
 fun { ctx; used } ab -> { ctx = split_ctx ctx ab; used }

let cubevar x fa : string list =
  let fa = string_of_sface fa in
  if fa = "" then [ x ] else [ x; fa ]

(* Look up an index variable to find a name for it. *)
let lookup : type mode a. a t -> (mode, a) index -> string list =
 fun { ctx; used = _ } (Index (x, fa, Plus_lock (_, comp))) ->
  let rec lookup : type a modality k n an.
      an ctx -> (a, modality, n, an) insert -> (k, n) sface -> string list =
   fun ctx x fa ->
    match (ctx, x) with
    | Snoc (ctx, _, _), Later x -> lookup ctx x fa
    | Snoc (_, Variables (_, mn, xs), fields), Now ->
        (* A self-variable with associated fields (added by "add_fields" for field-variable record display) being looked up directly, rather than through a field (which goes through "lookup_field"), cannot be displayed with field-variable syntax.  We signal this with the Self_used bug, which the unparser catches to fall back to self-variable syntax. *)
        (match fields with
        | Emp -> ()
        | Snoc _ -> Reporter.fatal Reporter.Code.Self_used);
        let (SFace_of_plus (_, fb, fc)) = sface_of_plus mn fa in
        cubevar (NICubeOf.find xs fc) fb
    | Emp, _ | Lock _, _ -> . in
  lookup (split_ctx ctx comp) x fa

(* Look up an index variable together with a field, to find a name for the combination, if there is one. *)
let lookup_field : type mode a. a t -> (mode, a) index -> string -> string list option =
 fun { ctx; used = _ } (Index (x, fa, Plus_lock (_, comp))) f ->
  let rec lookup : type a modality k n an.
      an ctx -> (a, modality, n, an) insert -> (k, n) sface -> string list option =
   fun ctx x fa ->
    match (ctx, x) with
    | Snoc (ctx, _, _), Later x -> lookup ctx x fa
    | Snoc (_, Variables (_, mn, _), fields), Now ->
        let open Monad.Ops (Monad.Maybe) in
        let (SFace_of_plus (_, fb, fc)) = sface_of_plus mn fa in
        let* _ = is_id_sface fc in
        let* y = Abwd.find_opt f fields in
        return (cubevar y fb)
    | Emp, _ | Lock _, _ -> . in
  lookup (split_ctx ctx comp) x fa

let rec primes n =
  if n <= 0 then ""
  else if n = 1 then "′"
  else if n = 2 then "″"
  else if n = 3 then "‴"
  else "⁗" ^ primes (n - 4)

(* Make a variable name unique, adding the new one to the list of used variables and returning it. *)
let uniquify : string -> StringSet.t -> string * [ `Original | `Renamed ] * StringSet.t =
 fun name used ->
  let rec until_unique k =
    let namek = name ^ primes k in
    if StringSet.mem namek used then until_unique (k + 1) else namek in
  let namen = until_unique 0 in
  (namen, `Renamed, used |> StringSet.add namen)

(* Create a new unique variable name, for a previously unnamed variable, from a list of possibilities.  The result is always "Renamed". *)
let new_name :
    string -> string list -> StringSet.t -> string * [ `Original | `Renamed ] * StringSet.t =
 fun face names used ->
  let rec go n = function
    | [] -> go (n + 1) names
    | name :: rest ->
        let namen = name ^ face ^ primes n in
        if StringSet.mem namen used then go n rest
        else (namen, `Renamed, used |> StringSet.add namen) in
  go 0 names

(* Make a variable name or placeholder unique, assigning an autogenerated name to placeholders.  Hint names attached to a placeholder are preferred over the globally configured default names. *)
let uniquify_opt : type a.
    (a -> binder_name * string) ->
    a ->
    StringSet.t ->
    string * [ `Original | `Renamed ] * StringSet.t =
 fun f name used ->
  match f name with
  | `Anon { names; fallback }, face ->
      new_name face (if fallback then names @ Display.variables () else names) used
  | `Named name, face -> uniquify (name ^ face) used

(* Do the same thing to a whole cube of variable names. *)
let uniquify_cube : type n left right a.
    (a -> binder_name * string) ->
    (left, n, a, right) NICubeOf.t ->
    StringSet.t ->
    (left, n, string, right) NICubeOf.t * StringSet.t =
 fun f names used ->
  (* Apparently we need to define the iteration function with an explicit type so that it ends up sufficiently polymorphic. *)
  let uniquify_nfamof : type m left.
      (left, m, a) NFamOf.t -> StringSet.t -> (left, m, string) NFamOf.t * StringSet.t =
   fun (NFamOf name) used ->
    let name, _, used = uniquify_opt f name used in
    (NFamOf name, used) in
  let open NICubeOf.Applicatic (Applicative.OfMonad (Monad.State (struct
    type t = StringSet.t
  end)))
  in
  mapM { map = (fun _ name used -> uniquify_nfamof name used) } names used

(* Add a new cube variable at a specified dimension, generating a fresh version of its name if necessary to avoid conflicts, and assigning an autogenerated name if it is unnamed. *)
let add_cube : type m n b. n D.t -> b t -> binder_name -> string * (b, (m, n) dim_entry) snoc t =
 fun n { ctx; used } name ->
  let name, _, used = uniquify_opt (fun x -> (x, "")) name used in
  ( name,
    { ctx = Snoc (ctx, Variables (n, D.plus_zero n, NICubeOf.singleton name), Abwd.empty); used } )

(* Add a single (cube) self-variable for a record type, with its fields exposed as named variables (mirroring Ctx.vis_fields and of_ordered_ctx).  The self-variable itself is anonymous: its fields are exposed so that field-projections of the self read back as field variables.  Unlike other bound variables, the field variables are NOT uniquified: their names are exactly the record's field names, which cannot be renamed without changing the meaning.  Hence if any field name clashes with a name already in scope (so that displaying it as a field variable would shadow that name), we return None, and the caller falls back to self-variable syntax.  On success, returns the field variable names (= the field names, in order) for use as the field patterns. *)
let add_fields : type b n m.
    n D.t -> b t -> string list -> ((b, (m, n) dim_entry) snoc t * string list) option =
 fun n { ctx; used } field_names ->
  let rec go used = function
    | [] -> Some (Abwd.empty, used)
    | f :: fs -> (
        if StringSet.mem f used then None
        else
          match go (StringSet.add f used) fs with
          | None -> None
          | Some (fields, used) -> Some (Snoc (fields, (f, f)), used)) in
  match go used field_names with
  | None -> None
  | Some (fields, used) ->
      let self_name, _, used = uniquify_opt (fun x -> (x, "")) (`Anon no_hints) used in
      Some
        ( {
            ctx = Snoc (ctx, Variables (n, D.plus_zero n, NICubeOf.singleton self_name), fields);
            used;
          },
          field_names )

(* Add a cube of variables, generating a fresh version of each of their names, and assigning autogenerated names to unnamed ones. *)
let add : type b m n. b t -> n variables -> (n, string) gvariables * (b, (m, n) dim_entry) snoc t =
 fun { ctx; used } (Variables (m, mn, names)) ->
  let names, used = uniquify_cube (fun x -> (x, "")) names used in
  let vars = Variables (m, mn, names) in
  (vars, { ctx = Snoc (ctx, vars, Abwd.empty); used })

(* Add a cube of already-named variables, generating a fresh version of each of their names. *)
let add_strings : type b m n.
    b t -> (n, string) gvariables -> (n, string) gvariables * (b, (m, n) dim_entry) snoc t =
 fun { ctx; used } (Variables (m, mn, names)) ->
  let names, used = uniquify_cube (fun x -> (`Named x, "")) names used in
  let vars = Variables (m, mn, names) in
  (vars, { ctx = Snoc (ctx, vars, Abwd.empty); used })

(* Add a partially-cube variable as a full cube of non-cube variables, with face names explicitly concatenated with the variable names, making all variables named. *)
let add_full : type b k mn.
    b t -> mn variables -> (mn, string) gvariables * (b, (k, mn) dim_entry) snoc t =
 fun { ctx; used } (Variables (m, m_n, xs)) ->
  let (Wrap (newxs, _)) =
    NICubeOf.NFold.build_left (D.plus_out m m_n)
      {
        build =
          (fun s i ->
            let (SFace_of_plus (_, sm, sn)) = sface_of_plus m_n s in
            let smstr = string_of_sface ~unicode:(Display.chars () = `Unicode) sm in
            Fwrap (NFamOf (NICubeOf.find xs sn, smstr), N.suc i));
      }
      N.zero in
  let names, used = uniquify_cube (fun x -> x) newxs used in
  let vars = Variables (D.zero, D.zero_plus (D.plus_out m m_n), names) in
  (vars, { ctx = Snoc (ctx, vars, Abwd.empty); used })

let rec add_lock : type a dom modality mode am.
    a t -> (a, mode, modality, dom, am) plus_lock -> am t =
 fun ctx -> function
  | Plus_lock (Zero _, Zero) -> ctx
  | Plus_lock (Suc (lock, Lock_lock _, Suc (Zero, Lock g1)), Suc (comp, Lock g2)) ->
      let Eq = Modality.Gen.tgt_uniq g1 g2 in
      let { ctx; used } = add_lock ctx (Plus_lock (lock, comp)) in
      { ctx = Lock ctx; used }

(* Extract all the names in a context, generating a fresh version of each name from left to right, including field access variables, and assigning autogenerated names to unnamed variables. *)
let rec of_ordered_ctx : type mode a b. (mode, a, b) Ctx.Ordered.t -> b t = function
  | Emp _ -> empty
  | Snoc (ctx, Vis { dim; plusdim; vars; fields; _ }, _) ->
      let { ctx; used } = of_ordered_ctx ctx in
      let vars, used = uniquify_cube (fun x -> (x, "")) vars used in
      let module M = Mbwd.Monadic (Monad.State (struct
        type t = StringSet.t
      end))
      in
      let fields, used =
        M.mmapM
          (fun [ (f, x) ] used ->
            let x, _, used = uniquify x used in
            ((Field.to_string f, x), used))
          [ Bwv.to_bwd fields ]
          used in
      { ctx = Snoc (ctx, Variables (dim, plusdim, vars), fields); used }
  | Snoc (ctx, Invis (_, bindings), _) ->
      (* Invisible variables are anonymous, but we can still give them hints from their types.  Since this is only for display, if anything goes wrong computing the type (e.g. the binding is an error placeholder) we just skip the hints. *)
      let hints =
        Reporter.try_with ~fatal:(fun _ -> no_hints) @@ fun () ->
        View.hints_of_ty (Ctx.Binding.value (CubeOf.find_top bindings)).ty in
      snd (add_cube (CubeOf.dim bindings) (of_ordered_ctx ctx) (`Anon hints))
  | Lock (ctx, _) ->
      let { ctx; used } = of_ordered_ctx ctx in
      { ctx = Lock ctx; used }
  | Parametric_lock ctx -> of_ordered_ctx ctx

let of_ctx : type mode a b. (mode, a, b) Ctx.t -> b t = function
  | Permute { ctx; _ } -> of_ordered_ctx ctx

(* Degenerate a name-context by a dimension r, mirroring Degctx.degctx: each variable cube is re-dimensioned from its intrinsic n-cube up to a (r+n)-cube, keeping the same base names (Variables.plus_variables changes only the substitution dimension, not the stored name cube).  This reproduces exactly the names that "of_ctx" would produce for the degenerated context, so it lets the renderer name the (degenerated) variables of a non-projectable higher codata field instance without rebuilding the value-level degenerate context. *)
(* TODO(about-merge): about walked its own (r, b, kb) Plusmap.t (Map_emp/Map_snoc) here; modal's plusmap is a different (Tctx.Plusmap.t-based) representation, so porting this name-context degeneration to modal (mirroring degctx.ml) is still pending.  Used for displaying non-projectable higher codata field instances (Cfd_deg); deferred. *)
let degenerate : type r b kb mode. r D.t -> (r, b, kb, mode) plusmap -> b t -> kb t =
 fun _r _pm _names -> fatal (Unimplemented "about-display of non-projectable higher codata fields (post-modal-merge)")

(* Add a cube of variables WITHOUT replacing them by fresh versions.  Should only be used when the variables have already been so replaced, as in the output of uniquify_vars below. *)
let unsafe_add : type k n b.
    b t -> (n, string) gvariables -> (string, string) Abwd.t -> (b, (k, n) dim_entry) snoc t =
 fun { ctx; used } vars fields -> { ctx = Snoc (ctx, vars, fields); used }

(* Given a Bwv of variables, proceed through from the *right* to mark them as visible or shadowed, accumulating a list of the visible names in a map.  Anonymous variables are marked as shadowed. *)
let rec used_vars : type n.
    (binder_name, n) Bwv.t ->
    StringSet.t ->
    (binder_name * [ `Visible | `Shadowed ], n) Bwv.t * StringSet.t =
 fun vars used ->
  let do_var (x : binder_name) used =
    match x with
    | `Named y ->
        if StringSet.mem y used then (x, `Shadowed, used) else (x, `Visible, used |> StringSet.add y)
    | `Anon _ -> (x, `Shadowed, used) in
  match vars with
  | Emp -> (Emp, used)
  | Snoc (vars, x) ->
      let x, o, used = do_var x used in
      let vars, used = used_vars vars used in
      (Snoc (vars, (x, o)), used)

type uniquified_vars = StringSet.t

let of_uniquified_vars used = { ctx = Emp; used }

(* Uniquify the names in a bwv from the *right*, thus leaving unchanged those that are still in lexical scope.  Also assigns an autogenerated name to previously unnamed variables.  Returns a Names object in the empty context that can then be used to build up a new one including those variables.  Since those variables have already been uniquified, they should be added in with unsafe_add.  (TODO: Can we avoid having to expose unsafe_add?) *)
let uniquify_vars : type a.
    (binder_name, a) Bwv.t -> (string * [ `Original | `Renamed ], a) Bwv.t * uniquified_vars =
 fun vars ->
  (* First we collect a map of all the visible names, also marking the given names as visible or shadowed. *)
  let vars, used = used_vars vars StringSet.empty in
  (* Then we proceed again from right to left, leaving the visible variables alone and replacing the shadowed ones with uniquified versions.  We do this in two passes to ensure that the uniquified version of a shadowed variable is never chosen in such a way as would shadow a variable to its left that already had that name. *)
  let rec go : type n.
      (binder_name * [ `Visible | `Shadowed ], n) Bwv.t ->
      StringSet.t ->
      (string * [ `Original | `Renamed ], n) Bwv.t * StringSet.t =
   fun vars used ->
    match vars with
    | Emp -> (Emp, used)
    | Snoc (vars, (x, sh)) ->
        let x, orig, used =
          match (x, sh) with
          | `Named x, `Visible -> (x, `Original, used)
          (* Anonymous variables are always marked as shadowed by used_vars, so the remaining cases are all renamed. *)
          | _, _ ->
              let x, _, used = uniquify_opt (fun x -> (x, "")) x used in
              (x, `Renamed, used) in
        let vars, used = go vars used in
        (Snoc (vars, (x, orig)), used) in
  let vars, used = go vars used in
  (vars, used)

type _ named_term = Named : 'a t * ('mode, 'a, kinetic) term -> 'mode named_term
