{` -*- narya-prog-args: ("-proofgeneral" "-spatial") -*- `}

axiom A : Type

` A modal *higher* codatatype: the "amazing right adjoint" √ of the identity
` type, composed with the ♭-modal structure.  The field .root has intrinsic
` dimension 1 and is checked (like a lower modal field) in a context locked by
` the right adjoint ♯; ♭ is parametric, so it filters none of the field's
` intrinsic dimensions.
def √♭A : Type ≔ codata [ (x :♭| _) .root.e : A ]

` A projection is written with the locking left adjoint ♭ as an ascription, and
` its type is keyed by the adjunction counit into the ambient context.

axiom s0 : √♭A

axiom s1 : √♭A

axiom s2 : Id √♭A s0 s1

echo (s2 :♭| _) .root.1

` The suffix can be omitted when it's the identity.
echo (s2 :♭| _) .root

` At higher dimensions we can project along each direction of a square, and the
` boundaries are themselves modal projections of the boundary squares.

axiom s00 : √♭A

axiom s01 : √♭A

axiom s10 : √♭A

axiom s11 : √♭A

axiom s02 : Id √♭A s00 s01

axiom s12 : Id √♭A s10 s11

axiom s20 : Id √♭A s00 s10

axiom s21 : Id √♭A s01 s11

axiom s22 : √♭A⁽ᵉᵉ⁾ s02 s12 s20 s21

echo (s22 :♭| _) .root.1

echo (s22 :♭| _) .root.2

` A comatch constructs an element of the modal higher codatatype.  Each
` component is checked behind a lock by the right adjoint ♯, in the context
` degenerated by the remaining dimensions of its partial bijection.

axiom a : A

def mk : √♭A ≔ [ .root.e ↦ a ]

` Projecting from its refl computes to the supplied component.

echo (refl mk :♭| _) .root.1

def mk_computes : Id A ((refl mk :♭| _) .root.1) a ≔ refl a

` A component may use a variable annotated by the right adjoint ♯, since it is
` checked behind a ♯-lock; being in the degenerated context, the variable
` appears as a cube, whence the face b.0.

def mk2 (b :♯| A) : √♭A ≔ [ .root.e ↦ b.0 ]

def mk2_computes : Id A ((refl (mk2 a) :♭| _) .root.1) a ≔ refl a
