{` -*- narya-prog-args: ("-proofgeneral" "-parametric" "-discrete-coreflector") -*- `}

` The types of the higher fields of a higher coinductive type are checked in a
` context degenerated by the field's dimension.  A *filtering-modal* parameter,
` however, is nonparametric with respect to that dimension, so it is NOT
` degenerated: the field type can mention such a parameter directly.

def ♭√ (A : ♭| Type) : Type ≔ codata [ x .root.e : A ]

axiom A : Type

` Projecting the higher field of a degenerate instance yields the un-degenerated
` A, rather than a square A⁽ᵉ⁾.
axiom s0 : ♭√ A
axiom s1 : ♭√ A
axiom s2 : Id (♭√ A) s0 s1
echo s2 .root.1

` Dually, we can construct an element by supplying an un-degenerated field value,
` and project it back out.
axiom a : A
def √a : ♭√ A ≔ [ .root.e ↦ a ]
echo refl √a .root.1

` A two-dimensional higher field behaves the same way: the ♭ parameter is not
` degenerated even by the 2-dimensional degeneracy of the field context.
def ♭√√ (A : ♭| Type) : Type ≔ codata [ x .rroot.ee : A ]
def √√a : ♭√√ A ≔ [ .rroot.ee ↦ a ]
echo refl (refl √√a) .rroot.12
