open Bwd
open Util
open Modal
open Reporter
open Dim
open Term
open Value
open Domvars
open Norm
open Readback
open Degctx

(* Raised by the comatch readback when it can't (yet) handle a field, so that "about" falls back to displaying the stored case tree (which unparse_comatch can render). *)
exception Comatch_fallback

(* Building the display node for a value-level codatatype or record type, for the "about" command.  This is the codata analogue of the datatype display builders in Readback (data_display_value / degenerate_data_display).  It lives here rather than in Readback because non-projectable higher-field instances are displayed in a context degenerated by their remaining dimensions (Degctx.degctx), and Degctx itself depends on Readback, so Readback cannot depend on Degctx.

   We introduce a single self-variable cube of the codatatype's dimension (via dom_vars, which gives its top face the fully-instantiated codatatype as its type), and read back the type of each field instance referring to it.  A lower field has exactly one instance; a higher field of intrinsic dimension i has one instance for each partial bijection between the codatatype's evaluation dimension and i.  Projectable instances (zero remaining dimensions) are read back in the self-variable context (Cfd); non-projectable ones (the declaration form ".e" and intermediate forms) are read back in a context degenerated by the remaining dimensions, recording the degeneration plus-map so the renderer can reconstruct the degenerated variable names (Cfd_deg).  The self-variable is added anonymously: readback ignores names (it produces de Bruijn terms), and the renderer chooses the displayed self-name itself. *)
let codata_display_value : type mode a b cm cn cc ca cet.
    (mode, a, b) Ctx.t ->
    (mode, kinetic) Value.value ->
    (mode, cm, cn, cc, ca, cet) Value.codata_args ->
    (mode, b) Term.canonical_display =
 fun ctx tm codata_args ->
  let eta = codata_args.eta in
  let evaldim = dim_env codata_args.env in
  let self_modality = Modality.id (Ctx.mode ctx) in
  match tm with
  | Neu { ty; _ } -> (
      match view_type (Lazy.force ty) "codata_display_value" with
      | Canonical (_, UU (_, mk), ins0, boundary) ->
          (* The universe has intrinsic dimension zero, so its substitution dimension equals its total dimension mk. *)
          let Eq = eq_of_ins_zero ins0 in
          let dom = TubeOf.plus_cube (val_of_norm_tube boundary) (CubeOf.singleton tm) in
          let selfvars, selfnfs = dom_vars ctx self_modality dom in
          let self_top = CubeOf.find_top selfvars in
          let self_top_ty = (Ctx.Binding.value (CubeOf.find_top selfnfs)).ty in
          let ctx = Ctx.cube_vis ctx self_modality None selfnfs in
          let fields =
            Bwd.fold_left
              (fun acc
                   (Term.CodatafieldAbwd.Entry
                      (type i)
                      ((fld, cf) : i Field.t * (i, mode * ca * cn * cet) Term.Codatafield.t)) ->
                match cf with
                | Term.Codatafield.Lower _ ->
                    let ety =
                      tyof_field (Ok self_top) self_top_ty fld ~shuf:Trivial (ins_zero evaldim)
                    in
                    Bwd.Snoc (acc, Term.Cfd (fld, [], readback_val ~sort:`Type ctx ety))
                | Term.Codatafield.Higher (_, _) ->
                    Seq.fold_left
                      (fun acc (Pbij_between (pbij : (cm, i, _) pbij)) ->
                        let (Pbij (fldins, fldshuf)) = pbij in
                        match D.compare_zero (left_shuffle fldshuf) with
                        | Zero ->
                            (* Projectable instance: read back in the self-variable context. *)
                            let Eq = eq_of_zero_shuffle fldshuf in
                            let ety =
                              tyof_field (Ok self_top) self_top_ty fld ~shuf:Trivial fldins in
                            Bwd.Snoc
                              ( acc,
                                Term.Cfd
                                  (fld, strings_of_pbij pbij, readback_val ~sort:`Type ctx ety) )
                        | Pos _ ->
                            (* Non-projectable instance: degenerate the context by the remaining dimensions and compute the field type there, recording the degeneration plus-map. *)
                            let r = left_shuffle fldshuf in
                            let (Degctx (plusmap, dctx, denv)) = degctx ctx r in
                            let termctx =
                              Lazy.force codata_args.termctx
                              <|> Anomaly "missing termctx for higher codata field" in
                            let shuf =
                              higher_codatafield_shuffleable ctx (length_env codata_args.env)
                                termctx denv r fldshuf in
                            let ety = tyof_field (Ok self_top) self_top_ty fld ~shuf fldins in
                            Bwd.Snoc
                              ( acc,
                                Term.Cfd_deg
                                  ( fld,
                                    strings_of_pbij pbij,
                                    r,
                                    plusmap,
                                    readback_val ~sort:`Type dctx ety ) ))
                      acc
                      (all_pbij_between evaldim (Field.dim fld)))
              Bwd.Emp codata_args.fields in
          Term.Codata_display { eta; dim = mk; fields }
      | _ -> fatal (Anomaly "type of codatatype/record is not a universe"))
  | _ -> fatal (Anomaly "codatatype/record value is not neutral")

(* Read back the *potential* value of a neutral, for the "about" command, into a display term: if it reduces (possibly under parameter abstractions) to a canonical type, a Canonical_display leaf wrapped in lambdas for the parameters; otherwise None, so the caller can fall back to displaying the stored case tree or the normal form.

   This relocates the former parser-side "unparse_potential": all the type-directed work (forcing the value, dispatching on the canonical kind, descending through parameter abstractions by applying to fresh variables) now lives here in core, producing an ordinary (potential) display term that unparse renders purely syntactically.  The parameter abstraction is reconstructed as a real Term.Lam carrying the definition's parameter name, so e.g. "about Vec" reads back as "A ↦ data [ … : Vec A … ]".  We descend only through zero-dimensional parameter abstractions; anything else (a genuine case tree with matches/comatches, a higher-dimensional abstraction, or a stuck neutral) returns None. *)
let rec readback_about : type mode a b.
    (mode, a, b) Ctx.t -> (mode, kinetic) Value.value -> (mode, b, potential) Term.term option =
 fun ctx value ->
  match value with
  | Neu { value = v; ty; _ } -> (
      match force_eval v with
      | Val (Value.Canonical { canonical; ins; _ }) -> (
          match canonical with
          | Data data_args -> (
              match (is_id_ins ins, D.compare_zero data_args.dim) with
              | Some _, Zero ->
                  let indexed = Fillvec.intended_pos data_args.indices in
                  Some (Term.Canonical_display (data_display_value ctx indexed data_args.constrs))
              | Some _, Pos _ ->
                  (* A degenerate (positive substitution dimension) datatype. *)
                  Some (Term.Canonical_display (degenerate_data_display ctx value data_args))
              | None, _ -> None)
          (* Codatatypes/records are handled uniformly whether 0-dimensional, intrinsically higher (Gel-like), or degenerate. *)
          | Codata codata_args ->
              Some (Term.Canonical_display (codata_display_value ctx value codata_args))
          | UU _ | Pi _ -> None)
      | Val (Lam (xs, _)) -> (
          (* A function (e.g. a parameterized datatype family): apply it to a fresh parameter variable and recurse, then re-abstract.  The parameter name comes from the lambda-abstraction (the definition), not the function-type (whose binder may be anonymous). *)
          match view_type (Lazy.force ty) "readback_about" with
          | Canonical (_, Pi (_, modality, doms, _), pins, _) -> (
              let Eq = eq_of_ins_zero pins in
              match D.compare_zero (CubeOf.dim doms) with
              | Zero -> (
                  let argvar, argnf = dom_vars ctx modality doms in
                  let ctx =
                    Ctx.cube_vis ctx modality (option_of_binder_name (top_variable xs)) argnf in
                  let value = apply_term value modality argvar in
                  match readback_about ctx value with
                  | None -> None
                  | Some body ->
                      Some
                        (Term.Lam (singleton_variables D.zero (top_variable xs), modality, body)))
              | Pos _ -> None)
          | _ -> None)
      | Val (Struct _) -> (
          (* A partially-evaluated struct: a comatch, or an eta-record tuple that hasn't reduced to a leaf (e.g. the componentwise transport "(Prod A B)⁽ᵉ⁾ .trr p", which is stuck on abstract A B).  Read it back type-directed via readback_comatch, passing the neutral (whose forced value is this struct) to serve as the self-variable, so its field types resolve even though the struct itself is a non-kinetic case-tree value.  If that gives up (e.g. on a higher comatch field with a non-empty closure environment), fall back to the application spine. *)
          try Some (!readback_comatch.rbc ctx value (Lazy.force ty)) with Comatch_fallback -> None)
      | _ -> None)
  | _ -> None

(* The forward-referenced implementation of comatch readback, type-directed by the codatatype, paralleling codata_display_value which reads back the field types.  It takes the *neutral* whose value is the comatch, and uses that neutral itself as the self-variable for computing each field's type with tyof_field (the neutral is already in the context, so no fresh self is needed; being Const-headed, it reads back without a context level).  A lower field is projected from the neutral directly.  A higher field's instances are read back from the comatch's stored terms, one per partial bijection: for each, we degenerate the readback context by the remaining dimensions, compute the field type there, evaluate the stored body term in the degenerated closure environment, and read it back.  For a top-level comatch the closure environment is empty, hence degeneration-invariant, so we evaluate directly in it; a non-empty closure environment (a partially-applied higher comatch) falls back to the stored case tree. *)
let readback_comatch_impl : type mode a z.
    (mode, z, a) Ctx.t -> (mode, kinetic) value -> (mode, kinetic) value -> (mode, a, potential) term
    =
 fun ctx neutral ty ->
  match (neutral, view_type ty "readback_comatch") with
  | ( Neu { value = nval; _ },
      Canonical
        (type mn m n)
        (( _,
           Codata (type c aa et) (codata_args : (mode, m, n, c, aa, et) codata_args),
           ins,
           tyargs ) :
          mode head
          * (mode, m, n) canonical
          * (mn, m, n) insertion
          * (D.zero, mn, mn, mode normal) TubeOf.t) ) -> (
      match force_eval nval with
      | Val (Struct { fields = comatch_fields; _ }) -> (
          (* The comatch is undegenerated when the codatatype instance's total dimension equals the intrinsic dimension.  A degenerate comatch (e.g. refl of a comatch) has a larger total dimension; displaying it as "[ … ]⁽ᵉ⁾" isn't representable as a term (Term.Act is kinetic, a comatch is potential) and a full readback of its degenerated instances is out of scope, so it falls back to the neutral's application spine ("refl r"), which is at least correct. *)
          match D.compare (TubeOf.inst tyargs) (cod_left_ins ins) with
          | Neq -> raise Comatch_fallback
          | Eq ->
              let dim = cod_left_ins ins in
              let evaldim = dim_env codata_args.env in
              (* Read back a lower field via the neutral-as-self: project the field out of the neutral, and use the neutral (a kinetic value, even though its potential value is this struct) to resolve the possibly-dependent field type. *)
              let lower_field (fld : D.zero Field.t) : (mode, a, potential) term =
                let ety = tyof_field (Ok neutral) ty fld ~shuf:Trivial (ins_zero evaldim) in
                let body = field_term neutral fld (ins_zero dim) in
                Term.Realize (readback_at ctx body ety) in
              (* The return-type annotation keeps the field-map's eta ('et) polymorphic.  The higher-field branch below constrains 'et = no_eta, but only locally where it is actually reached; so a record (where 'et = has_eta and there are no higher fields) reads back its (non-leaf) tuple value through exactly the same code.  This is what lets "about (Prod A B)⁽ᵉ⁾ .trr p" display the componentwise transport rather than the stuck spine. *)
              let fields =
                Mbwd.map
                  (fun (Term.CodatafieldAbwd.Entry
                          (type i)
                          ((fld, cf) : i Field.t * (i, mode * aa * n * et) Term.Codatafield.t)) :
                       (mode * (mn * a * potential * et)) Term.StructfieldAbwd.entry ->
                    match cf with
                    | Term.Codatafield.Lower _ ->
                        Term.StructfieldAbwd.Entry
                          (fld, Term.Structfield.Lower (lower_field fld, `Labeled))
                    | Term.Codatafield.Higher _ -> (
                        match Value.StructfieldAbwd.find_opt comatch_fields fld with
                        | Found (Value.Structfield.Higher (lazy hd)) -> (
                            (* We handle only an undegenerated comatch (identity deg) with an empty closure environment (a top-level comatch), where the stored term can be evaluated directly in the empty environment.  A degenerate comatch (e.g. refl of a comatch) or a partially-applied one falls back to the stored case tree. *)
                            match
                              (hd.env, D.compare dim (D.plus_right hd.plusdim), is_id_deg hd.deg)
                            with
                            | Emp _, Eq, Some _ ->
                                let pbm =
                                  Term.PlusPbijmap.build dim (Field.dim fld)
                                    {
                                      build =
                                        (fun (type r)
                                          (pbij : (m, i, r) pbij)
                                          :
                                          (r, mode * a) Term.PlusFam.t
                                        ->
                                          match Term.PlusPbijmap.find pbij hd.terms with
                                          | None -> raise Comatch_fallback
                                          | Some (Term.PlusFam.PlusFam (stored_pm, term)) -> (
                                              (* The closure environment is empty, so degenerating it leaves it empty: the stored plus-map is the proj-only one (matched below) and the stored term lives over the empty context, so it can be evaluated directly in hd.env. *)
                                              match stored_pm with
                                              | Suc
                                                  ( Zero (Eq Unit),
                                                    Inject (Plus_proj _),
                                                    Suc (Zero, Proj _) ) ->
                                                  let (Pbij (fldins, fldshuf)) = pbij in
                                                  let r = left_shuffle fldshuf in
                                                  let (Degctx (plusmap, dctx, denv)) = degctx ctx r in
                                                  let ety =
                                                    match D.compare_zero r with
                                                    | Zero ->
                                                        let Eq = eq_of_zero_shuffle fldshuf in
                                                        tyof_field (Ok neutral) ty fld ~shuf:Trivial
                                                          fldins
                                                    | Pos _ ->
                                                        let termctx =
                                                          Lazy.force codata_args.termctx
                                                          <|> Anomaly
                                                                "missing termctx for higher comatch"
                                                        in
                                                        let shuf =
                                                          higher_codatafield_shuffleable ctx
                                                            (length_env codata_args.env) termctx denv
                                                            r fldshuf in
                                                        tyof_field (Ok neutral) ty fld ~shuf fldins
                                                  in
                                                  let body = eval hd.env term in
                                                  Some
                                                    (Term.PlusFam.PlusFam
                                                       (plusmap, readback_eval dctx body ety))
                                              | _ -> raise Comatch_fallback));
                                    } in
                                Term.StructfieldAbwd.Entry (fld, Term.Structfield.Higher pbm)
                            | _ -> raise Comatch_fallback)
                        | _ -> raise Comatch_fallback))
                  codata_args.fields in
              Term.Struct { eta = codata_args.eta; dim; fields; energy = Potential })
      | _ -> fatal (Anomaly "comatch readback: neutral value is not a struct"))
  | _ -> fatal (Anomaly "comatch readback: not a neutral at a codatatype")

let () = readback_comatch := { rbc = readback_comatch_impl }
