open Bwd
open Reporter
open Dim
open Term
open Value
open Domvars
open Norm
open Readback
open Degctx

(* Building the display node for a value-level codatatype or record type, for the "about" command.  This is the codata analogue of the datatype display builders in Readback (data_display_value / degenerate_data_display).  It lives here rather than in Readback because non-projectable higher-field instances are displayed in a context degenerated by their remaining dimensions (Degctx.degctx), and Degctx itself depends on Readback, so Readback cannot depend on Degctx.

   We introduce a single self-variable cube of the codatatype's dimension (via dom_vars, which gives its top face the fully-instantiated codatatype as its type), and read back the type of each field instance referring to it.  A lower field has exactly one instance; a higher field of intrinsic dimension i has one instance for each partial bijection between the codatatype's evaluation dimension and i.  Projectable instances (zero remaining dimensions) are read back in the self-variable context (Cfd); non-projectable ones (the declaration form ".e" and intermediate forms) are read back in a context degenerated by the remaining dimensions, recording the degeneration plus-map so the renderer can reconstruct the degenerated variable names (Cfd_deg).  The self-variable is added anonymously: readback ignores names (it produces de Bruijn terms), and the renderer chooses the displayed self-name itself. *)
let codata_display_value : type a b cm cn cc ca cet.
    (a, b) Ctx.t ->
    kinetic Value.value ->
    (cm, cn, cc, ca, cet) Value.codata_args ->
    b Term.canonical_display =
 fun ctx tm codata_args ->
  let eta = codata_args.eta in
  let evaldim = dim_env codata_args.env in
  match tm with
  | Neu { ty; _ } -> (
      match view_type (Lazy.force ty) "codata_display_value" with
      | Canonical (_, UU mk, ins0, boundary) ->
          (* The universe has intrinsic dimension zero, so its substitution dimension equals its total dimension mk. *)
          let Eq = eq_of_ins_zero ins0 in
          let dom = TubeOf.plus_cube (val_of_norm_tube boundary) (CubeOf.singleton tm) in
          let selfvars, selfnfs = dom_vars ctx dom in
          let self_top = CubeOf.find_top selfvars in
          let self_top_ty = (Ctx.Binding.value (CubeOf.find_top selfnfs)).ty in
          let ctx = Ctx.cube_vis ctx None selfnfs in
          let fields =
            Bwd.fold_left
              (fun acc
                   (Term.CodatafieldAbwd.Entry
                      (type i)
                      ((fld, cf) : i Field.t * (i, ca * cn * cet) Term.Codatafield.t)) ->
                match cf with
                | Term.Codatafield.Lower _ ->
                    let ety =
                      tyof_field (Ok self_top) self_top_ty fld ~shuf:Trivial (ins_zero evaldim)
                    in
                    Bwd.Snoc (acc, Term.Cfd (fld, [], readback_val ~sort:`Type ctx ety))
                | Term.Codatafield.Higher (_, _) ->
                    Seq.fold_left
                      (fun acc (Pbij_between (pbij : (cm, i, _) pbij)) ->
                        let (Pbij (fldins, fldshuf)) = pbij in
                        match D.compare_zero (left_shuffle fldshuf) with
                        | Zero ->
                            (* Projectable instance: read back in the self-variable context. *)
                            let Eq = eq_of_zero_shuffle fldshuf in
                            let ety =
                              tyof_field (Ok self_top) self_top_ty fld ~shuf:Trivial fldins in
                            Bwd.Snoc
                              ( acc,
                                Term.Cfd
                                  (fld, strings_of_pbij pbij, readback_val ~sort:`Type ctx ety) )
                        | Pos _ ->
                            (* Non-projectable instance: degenerate the context by the remaining dimensions and compute the field type there, recording the degeneration plus-map. *)
                            let r = left_shuffle fldshuf in
                            let (Degctx (plusmap, dctx, denv)) = degctx ctx r in
                            let termctx =
                              Lazy.force codata_args.termctx
                              <|> Anomaly "missing termctx for higher codata field" in
                            let shuf =
                              higher_codatafield_shuffleable ctx (length_env codata_args.env)
                                termctx denv r fldshuf in
                            let ety = tyof_field (Ok self_top) self_top_ty fld ~shuf fldins in
                            Bwd.Snoc
                              ( acc,
                                Term.Cfd_deg
                                  ( fld,
                                    strings_of_pbij pbij,
                                    r,
                                    plusmap,
                                    readback_val ~sort:`Type dctx ety ) ))
                      acc
                      (all_pbij_between evaldim (Field.dim fld)))
              Bwd.Emp codata_args.fields in
          Term.Codata_display { eta; dim = mk; fields }
      | _ -> fatal (Anomaly "type of codatatype/record is not a universe"))
  | _ -> fatal (Anomaly "codatatype/record value is not neutral")
