open Util
open Perhaps
open Tbwd
open Tlist
open Dim
open Modal

(* To first approximation, type-level contexts form the free category generated by (1) modality generators, for locks and (2) variables, at a given mode (which is both the "source" and "target"), with a given dimension, and annotated by a given modality.  The "mode of the context" is its *source* as a morphism in this free category.

   Its target, in this free category, would be the mode of the empty context from which it was built.  But we are never interested in that, so it would be annoying to have to track it all the time.  Therefore, we add an extra dummy object and generating morphism to it from every mode, so that every context can have the same target. *)

type ('x, 'a) dim_entry = private Dim_entry_dummy
type 'a lock_entry = private Lock_entry_dummy
type 'a proj = private Proj_dummy

module ModeUnit = struct
  type _ t = Mode : 'a Mode.t -> 'a t | Unit : unit t

  let compare : type a b. a t -> b t -> (a, b) Eq.compare =
   fun a b ->
    match (a, b) with
    | Mode a, Mode b -> Mode.compare a b
    | Unit, Unit -> Eq
    | _ -> Neq
end

module TEntry = struct
  module Obj = ModeUnit

  type (_, _, _) t =
    | Dim :
        ('dom, 'modality, 'mode) Modality.t * 'a D.t
        -> ('mode, ('modality, 'a) dim_entry, 'mode) t
    | Lock : ('dom, 'mu, 'cod) Modality.gen -> ('dom, 'mu lock_entry, 'cod) t
    | Proj : 'mode Mode.t -> ('mode, 'mode proj, unit) t

  let src : type src m tgt. (src, m, tgt) t -> src Obj.t = function
    | Dim (x, _) -> Mode (Modality.tgt x)
    | Lock m -> Mode (Modality.Gen.src m)
    | Proj m -> Mode m

  let tgt : type src m tgt. (src, m, tgt) t -> tgt Obj.t = function
    | Dim (x, _) -> Mode (Modality.tgt x)
    | Lock m -> Mode (Modality.Gen.tgt m)
    | Proj _ -> Unit

  let src_uniq : type src1 m tgt1 src2 tgt2.
      (src1, m, tgt1) t -> (src2, m, tgt2) t -> (src1, src2) Eq.t =
   fun m1 m2 ->
    match (m1, m2) with
    | Dim (m1, _), Dim (m2, _) -> Modality.tgt_uniq m1 m2
    | Lock m1, Lock m2 -> Modality.Gen.src_uniq m1 m2
    | Proj _, Proj _ -> Eq

  let tgt_uniq : type src1 m tgt1 src2 tgt2.
      (src1, m, tgt1) t -> (src2, m, tgt2) t -> (tgt1, tgt2) Eq.t =
   fun m1 m2 ->
    match (m1, m2) with
    | Dim (m1, _), Dim (m2, _) -> Modality.tgt_uniq m1 m2
    | Lock m1, Lock m2 -> Modality.Gen.tgt_uniq m1 m2
    | Proj _, Proj _ -> Eq

  let compare : type d1 c1 d2 c2 g1 g2.
      (d1, g1, c1) t -> (d2, g2, c2) t -> (d1 * g1 * c1, d2 * g2 * c2) Eq.compare =
   fun x y ->
    match (x, y) with
    | Dim (x, a), Dim (y, b) -> (
        match (Modality.compare x y, D.compare a b) with
        | Eq, Eq -> Eq
        | _ -> Neq)
    | Lock x, Lock y -> (
        match Modality.Gen.compare x y with
        | Eq -> Eq
        | Neq -> Neq)
    | Proj m, Proj n -> (
        match Mode.compare m n with
        | Eq -> Eq
        | Neq -> Neq)
    | _ -> Neq
end

module Tctxcat = Path.Make (TEntry)

type 'mode emp = (unit Tctxcat.id, 'mode proj) Tctxcat.suc
type 'mode id = 'mode Tctxcat.id
type ('x, 'y) suc = ('x, 'y) Tctxcat.suc

module Tctx = struct
  include Tctxcat

  type nonrec ('mode, 'a) t = ('mode, 'a, unit) t

  let emp : type mode. mode Mode.t -> (mode, mode emp) t =
   fun mode -> Path (Suc (Zero, Proj mode), Unit)
end
(* We can compose all the locks in a tctx to produce a modality.  This *doesn't* work on the extra object, though, so we raise an error if it's applied to that.  So this isn't used on a whole context, only on context extensions.  *)

module Locksmap = struct
  module Dom = TEntry
  module Cod = Modality

  module Obj = struct
    module Dom = ModeUnit
    module Cod = Mode

    type (_, _) t = Eq : 'a Mode.t -> ('a, 'a) t

    let dom : type a x. (a, x) t -> a Dom.t = fun (Eq a) -> Mode a
    let cod : type a x. (a, x) t -> x Cod.t = fun (Eq a) -> a

    type _ exists = Exists : ('a, 'x) t -> 'a exists

    let exists : type a. a Dom.t -> a exists = function
      | Mode a -> Exists (Eq a)
      | Unit -> raise (Failure "IdModeUnit.exists on Unit")

    let uniq : type a x1 x2. (a, x1) t -> (a, x2) t -> (x1, x2) Eq.t =
     fun x1 x2 ->
      match (x1, x2) with
      | Eq _, Eq _ -> Eq
  end

  type (_, _, _, _, _, _) t =
    | Locks_dim :
        ('dom, 'annote, 'mode) Modality.t * 'a D.t
        -> ('mode, ('annote, 'a) dim_entry, 'mode, 'mode, 'mode Modality.id, 'mode) t
    | Locks_lock :
        ('x, 'm, 'y) Modality.gen
        -> ('x, 'm lock_entry, 'y, 'x, ('y Modality.id, 'm) snoc, 'y) t

  let dom : type a m b x n y. (a, m, b, x, n, y) t -> (a, m, b) Dom.t = function
    | Locks_dim (x, a) -> Dim (x, a)
    | Locks_lock m -> Lock m

  let cod : type a m b x n y. (a, m, b, x, n, y) t -> (x, n, y) Cod.t = function
    | Locks_dim (x, _) -> Modality.id (Modality.tgt x)
    | Locks_lock m -> Modality.of_gen m

  let src : type a m b x n y. (a, m, b, x, n, y) t -> (a, x) Obj.t = function
    | Locks_dim (x, _) -> Eq (Modality.tgt x)
    | Locks_lock m -> Eq (Modality.Gen.src m)

  let tgt : type a m b x n y. (a, m, b, x, n, y) t -> (b, y) Obj.t = function
    | Locks_dim (x, _) -> Eq (Modality.tgt x)
    | Locks_lock m -> Eq (Modality.Gen.tgt m)

  type (_, _, _) exists = Exists : ('a, 'm, 'b, 'x, 'n, 'y) t -> ('a, 'm, 'b) exists

  let exists : type a m b. (a, m, b) Dom.t -> (a, m, b) exists = function
    | Dim (x, a) -> Exists (Locks_dim (x, a))
    | Lock m -> Exists (Locks_lock m)
    | Proj _ -> raise (Failure "Locksmap.exists on Proj")

  let uniq : type a m b x1 x2 y1 y2 n1 n2.
      (a, m, b, x1, n1, y1) t -> (a, m, b, x2, n2, y2) t -> (x1 * n1 * y1, x2 * n2 * y2) Eq.t =
   fun f1 f2 ->
    match (f1, f2) with
    | Locks_dim (_, _), Locks_dim (_, _) -> Eq
    | Locks_lock _, Locks_lock _ -> Eq
end

module Locks = Path.Hom (TEntry) (Modality) (Locksmap)

(* Make a modality into a Tctx consisting only of locks. *)

module Lockmap = struct
  module Dom = Modality.Gen
  module Cod = Tctxcat

  module Obj = struct
    module Dom = Mode
    module Cod = ModeUnit

    type (_, _) t = Eq : 'a Mode.t -> ('a, 'a) t

    let dom : type a x. (a, x) t -> a Dom.t = fun (Eq a) -> a
    let cod : type a x. (a, x) t -> x Cod.t = fun (Eq a) -> Mode a

    type _ exists = Exists : ('a, 'x) t -> 'a exists

    let exists : type a. a Dom.t -> a exists = fun a -> Exists (Eq a)

    let uniq : type a x1 x2. (a, x1) t -> (a, x2) t -> (x1, x2) Eq.t =
     fun x1 x2 ->
      match (x1, x2) with
      | Eq _, Eq _ -> Eq
  end

  type (_, _, _, _, _, _) t =
    | Lock_lock :
        ('x, 'm, 'y) Modality.gen
        -> ('x, 'm, 'y, 'x, ('y Tctx.id, 'm lock_entry) snoc, 'y) t

  let dom : type a m b x n y. (a, m, b, x, n, y) t -> (a, m, b) Dom.t = function
    | Lock_lock m -> m

  let cod : type a m b x n y. (a, m, b, x, n, y) t -> (x, n, y) Cod.t = function
    | Lock_lock m -> Tctx.suc (Tctx.id (Mode (Modality.Gen.tgt m))) (Lock m)

  let src : type a m b x n y. (a, m, b, x, n, y) t -> (a, x) Obj.t = function
    | Lock_lock m -> Eq (Modality.Gen.src m)

  let tgt : type a m b x n y. (a, m, b, x, n, y) t -> (b, y) Obj.t = function
    | Lock_lock m -> Eq (Modality.Gen.tgt m)

  type (_, _, _) exists = Exists : ('a, 'm, 'b, 'x, 'n, 'y) t -> ('a, 'm, 'b) exists

  let exists : type a m b. (a, m, b) Dom.t -> (a, m, b) exists = fun m -> Exists (Lock_lock m)

  let uniq : type a m b x1 x2 y1 y2 n1 n2.
      (a, m, b, x1, n1, y1) t -> (a, m, b, x2, n2, y2) t -> (x1 * n1 * y1, x2 * n2 * y2) Eq.t =
   fun f1 f2 ->
    match (f1, f2) with
    | Lock_lock _, Lock_lock _ -> Eq
end

module Lock = Path.Hom (Modality.Gen) (Tctxcat) (Lockmap)
open Tctx

(* Sometimes it's important to know whether a partial context starts with a lock, or starts with a lock if it is nonempty. *)

type _ starts_with_lock =
  | Lock : ('mode id, 'mu lock_entry) suc starts_with_lock
  | Suc : 'b starts_with_lock -> ('b, 'g) suc starts_with_lock

type (_, _) starts_with_lock_or_empty =
  | Starts : 'b starts_with_lock -> ('b, some) starts_with_lock_or_empty
  | Empty : ('mode id, none) starts_with_lock_or_empty

type _ any_starts_with_lock_or_empty =
  | Any : ('b, 'p) starts_with_lock_or_empty -> 'b any_starts_with_lock_or_empty

let rec lock_starts_with_lock_or_empty : type x m y t.
    (x, m, y, x, t, y) Lock.t -> t any_starts_with_lock_or_empty = function
  | Zero _ -> Any Empty
  | Suc (l, Lock_lock _, Suc (Zero, _)) -> (
      let Eq _, Eq _ = (Lock.src l, Lock.tgt l) in
      match lock_starts_with_lock_or_empty l with
      | Any (Starts s) -> Any (Starts (Suc s))
      | Any Empty -> Any (Starts Lock))

let rec starts_with_lock_left : type x a y b z ab p.
    (x, b, y, a, z, ab) Tctx.comp ->
    (ab, p) starts_with_lock_or_empty ->
    a any_starts_with_lock_or_empty =
 fun ab l ->
  match (ab, l) with
  | Zero, _ -> Any l
  | Suc (Zero, _), Starts Lock -> Any Empty
  | Suc (ab, _), Starts (Suc l) -> starts_with_lock_left ab (Starts l)

(* Making a modality into a context, and then extracting a modality, is the identity. *)

let rec locks_lock : type a m b tm. (a, m, b, a, tm, b) Lock.t -> (a, tm, b, a, m, b) Locks.t =
  function
  | Zero (Eq a) -> Zero (Eq a)
  | Suc (l, Lock_lock g, Suc (Zero, Lock _)) -> Suc (locks_lock l, Locks_lock g, Suc (Zero, g))

(* We can append a modal lock to a tctx by making the modality into a tctx and then appending it. *)

type (_, _, _, _, _) plus_lock =
  | Plus_lock :
      ('dom, 'modality, 'mode, 'dom, 'mlock, 'mode) Lock.t
      * ('dom, 'mlock, 'mode, 'ctx, unit, 'newctx) comp
      -> ('ctx, 'mode, 'modality, 'dom, 'newctx) plus_lock

type (_, _, _, _) has_plus_lock =
  | Has_plus_lock :
      ('ctx, 'mode, 'modality, 'dom, 'newctx) plus_lock
      -> ('ctx, 'dom, 'modality, 'mode) has_plus_lock

let plus_lock : type ctx dom modality mode.
    (dom, modality, mode) Modality.t -> (ctx, dom, modality, mode) has_plus_lock =
 fun m ->
  let (Exists cm) = Lock.exists m in
  let Eq _, Eq _ = (Lock.src cm, Lock.tgt cm) in
  let (Comp bm) = Tctx.comp (Lock.cod cm) in
  Has_plus_lock (Plus_lock (cm, bm))

let plus_no_lock : type ctx mode. mode Mode.t -> (ctx, mode, mode Modality.id, mode, ctx) plus_lock
    =
 fun mode -> Plus_lock (Zero (Eq mode), Zero)

let plus_lock_suc : type ctx mode modality dom newctx x m.
    (ctx, mode, modality, dom, newctx) plus_lock ->
    (x, m, dom) Modality.gen ->
    (ctx, mode, (modality, m) suc, x, (newctx, m lock_entry) suc) plus_lock =
 fun (Plus_lock (lock, comp)) m ->
  Plus_lock (Suc (lock, Lock_lock m, Suc (Zero, Lock m)), Suc (comp, Lock m))

let plus_lock_out : type mode ctx modality dom newctx.
    (mode, ctx) Tctx.t -> (ctx, mode, modality, dom, newctx) plus_lock -> (dom, newctx) Tctx.t =
 fun ctx (Plus_lock (_, comp)) -> Tctx.comp_out ctx comp

let plus_lock_modality : type ctx mode modality dom newctx.
    (ctx, mode, modality, dom, newctx) plus_lock -> (dom, modality, mode) Modality.t =
 fun (Plus_lock (l, _)) -> Lock.dom l

(* Append some arbitrary context that, if nonempty, starts with a lock, and has locks that compose to a given result. *)

type (_, _, _, _, _) plus_with_locks =
  | Plus_with_locks :
      ('c, 'p) starts_with_lock_or_empty
      * ('dom, 'c, 'mode, 'a, unit, 'ac) Tctx.comp
      * ('dom, 'c, 'mode, 'dom, 'modality, 'mode) Locks.t
      -> ('a, 'mode, 'modality, 'dom, 'ac) plus_with_locks

let plus_with_locks_of_plus_lock : type a y m x am.
    (a, y, m, x, am) plus_lock -> (a, y, m, x, am) plus_with_locks =
 fun (Plus_lock (lm, bm)) ->
  let llm = locks_lock lm in
  let (Any s) = lock_starts_with_lock_or_empty lm in
  Plus_with_locks (s, bm, llm)

let plus_with_no_locks : type b mode. mode Mode.t -> (b, mode, mode id, mode, b) plus_with_locks =
 fun mode -> Plus_with_locks (Empty, Zero, Zero (Eq mode))

let plus_with_locks_lock : type a cod modality mode gen dom ac.
    (a, cod, modality, mode, ac) plus_with_locks ->
    (dom, gen, mode) Modality.gen ->
    (a, cod, (modality, gen) suc, dom, (ac, gen lock_entry) suc) plus_with_locks =
 fun (Plus_with_locks (type c p) ((s, c, l) : (c, p) starts_with_lock_or_empty * _ * _)) g ->
  let (Any s) : (c, gen lock_entry) suc any_starts_with_lock_or_empty =
    match s with
    | Empty -> Any (Starts Lock)
    | Starts s -> Any (Starts (Suc s)) in
  Plus_with_locks (s, Suc (c, Lock g), Suc (l, Locks_lock g, Suc (Zero, g)))

let plus_with_locks_dim : type a cod modality mode dom ac annote n.
    (a, cod, modality, mode, ac) plus_with_locks ->
    (dom, annote, mode) Modality.t ->
    n D.t ->
    (a, cod, modality, mode, (ac, (annote, n) dim_entry) suc) plus_with_locks option =
 fun (Plus_with_locks (type c p) ((s, c, l) : (c, p) starts_with_lock_or_empty * _ * _)) annote n ->
  match s with
  | Empty -> None
  | Starts s ->
      Some
        (Plus_with_locks
           (Starts (Suc s), Suc (c, Dim (annote, n)), Suc (l, Locks_dim (annote, n), Zero)))

(* Lists of variable-annotation modalities, at the same mode (their codomain), to be made into lists of variables by combining with a dimension. *)

module VarAnnote = struct
  module Obj = Mode

  type (_, _, _) t = Annote : ('dom, 'modality, 'mode) Modality.t -> ('mode, 'modality, 'mode) t

  let src : type a m b. (a, m, b) t -> a Obj.t = fun (Annote m) -> Modality.tgt m
  let tgt : type a m b. (a, m, b) t -> b Obj.t = fun (Annote m) -> Modality.tgt m

  let src_uniq : type a1 a2 m b1 b2. (a1, m, b1) t -> (a2, m, b2) t -> (a1, a2) Eq.t =
   fun (Annote m1) (Annote m2) -> Modality.tgt_uniq m1 m2

  let tgt_uniq : type a1 a2 m b1 b2. (a1, m, b1) t -> (a2, m, b2) t -> (b1, b2) Eq.t =
   fun (Annote m1) (Annote m2) -> Modality.tgt_uniq m1 m2

  let compare : type a1 a2 m1 m2 b1 b2.
      (a1, m1, b1) t -> (a2, m2, b2) t -> (a1 * m1 * b1, a2 * m2 * b2) Eq.compare =
   fun (Annote m1) (Annote m2) ->
    match Modality.compare m1 m2 with
    | Eq -> Eq
    | Neq -> Neq
end

module VarAnnotations = Path.Make (VarAnnote)

module VarAnnotator = struct
  module Param = D
  module Dom = VarAnnote
  module Cod = TEntry

  module Obj = struct
    module Param = Param
    module Dom = Mode
    module Cod = ModeUnit

    type (_, _, _) t = Eq : 'a Mode.t -> ('n, 'a, 'a) t

    let dom : type p a x. (p, a, x) t -> a Dom.t = fun (Eq a) -> a
    let cod : type p a x. p Param.t -> (p, a, x) t -> x Cod.t = fun _ (Eq a) -> Mode a

    type (_, _) exists = Exists : ('p, 'a, 'x) t -> ('p, 'a) exists

    let exists : type p a. p Param.t -> a Dom.t -> (p, a) exists = fun _ a -> Exists (Eq a)

    let uniq : type p a x1 x2. (p, a, x1) t -> (p, a, x2) t -> (x1, x2) Eq.t =
     fun x1 x2 ->
      match (x1, x2) with
      | Eq _, Eq _ -> Eq
  end

  type (_, _, _, _, _, _, _) t =
    | Annotate :
        ('dom, 'modality, 'mode) Modality.t
        -> ('n, 'mode, 'modality, 'mode, 'mode, ('modality, 'n) dim_entry, 'mode) t

  type (_, _, _, _) exists =
    | Exists : ('param, 'a, 'm, 'b, 'x, 'n, 'y) t -> ('param, 'a, 'm, 'b) exists

  let dom : type param a m b x n y. (param, a, m, b, x, n, y) t -> (a, m, b) Dom.t =
   fun (Annotate m) -> Annote m

  let cod : type param a m b x n y. param Param.t -> (param, a, m, b, x, n, y) t -> (x, n, y) Cod.t
      =
   fun p (Annotate m) -> Dim (m, p)

  let src : type param a m b x n y. (param, a, m, b, x, n, y) t -> (param, a, x) Obj.t =
   fun (Annotate m) -> Eq (Modality.tgt m)

  let tgt : type param a m b x n y. (param, a, m, b, x, n, y) t -> (param, b, y) Obj.t =
   fun (Annotate m) -> Eq (Modality.tgt m)

  let exists : type param a m b. param Param.t -> (a, m, b) Dom.t -> (param, a, m, b) exists =
   fun _ (Annote m) -> Exists (Annotate m)

  let uniq : type param a m b x1 n1 y1 x2 n2 y2.
      (param, a, m, b, x1, n1, y1) t ->
      (param, a, m, b, x2, n2, y2) t ->
      (x1 * n1 * y1, x2 * n2 * y2) Eq.t =
   fun (Annotate _) (Annotate _) -> Eq
end

module VarAnnotate = Path.Fmap (VarAnnote) (TEntry) (VarAnnotator)

(* Insertions and permutations.  We only allow inserting and permuting dimensions in between locks; this makes sense because dimensions are all endomorphisms in this free category. *)

type (_, _, _, _) insert =
  | Now : ('a, 'x, 'n, ('a, ('x, 'n) dim_entry) snoc) insert
  | Later :
      ('a, 'x, 'n, 'b) insert
      -> (('a, ('y, 'k) dim_entry) snoc, 'x, 'n, ('b, ('y, 'k) dim_entry) snoc) insert

let rec insert_dom : type a x n b mode. (a, x, n, b) insert -> (mode, b) Tctx.t -> (mode, a) Tctx.t
    =
 fun i b ->
  match i with
  | Now ->
      let (Path (Suc (a, Dim _), mode)) = b in
      Path (a, mode)
  | Later i ->
      let (Path (Suc (b, Dim (x, n)), mode)) = b in
      let a = insert_dom i (Path (b, mode)) in
      Tctx.suc a (Dim (x, n))

let rec inserted : type a modality n b mode.
    (a, modality, n, b) insert -> (mode, b) Tctx.t -> (modality, mode) Modality.has_src * n D.t =
 fun i b ->
  match i with
  | Now ->
      let (Path (Suc (_, Dim (modality, n)), _)) = b in
      (Wrap modality, n)
  | Later i ->
      let (Path (Suc (b, Dim _), mode)) = b in
      inserted i (Path (b, mode))

(* If the domain of an insertion is broken up as a composition, we can sometimes likewise break up its codomain.  This is always possible if the right factor in the composition starts with a lock. *)

type (_, _, _, _, _, _, _, _) insert_from_comp =
  | Insert_from_comp :
      ('x, 'c, 'y, 'a, 'z, 'ac) Tctx.comp * 'c starts_with_lock * ('b, 'm, 'n, 'c) insert
      -> ('x, 'y, 'a, 'z, 'ac, 'b, 'm, 'n) insert_from_comp

let rec insert_from_comp : type b m n a ab ac w x y z.
    (w, m, x) Modality.t ->
    n D.t ->
    (ab, m, n, ac) insert ->
    (x, b, y, a, z, ab) Tctx.comp ->
    b starts_with_lock ->
    (x, y, a, z, ac, b, m, n) insert_from_comp =
 fun m n i ab b ->
  match i with
  | Now -> Insert_from_comp (Suc (ab, Dim (m, n)), Suc b, Now)
  | Later i -> (
      match (b, ab) with
      | Suc b, Suc (ab, Dim (p, k)) ->
          let (Insert_from_comp (ac, c, j)) = insert_from_comp m n i ab b in
          Insert_from_comp (Suc (ac, Dim (p, k)), Suc c, Later j))

(* Inserting doesn't change the total locks *)

let rec insert_locks : type a p n b w x y m.
    (w, p, x) Modality.t ->
    n D.t ->
    (a, p, n, b) insert ->
    (x, a, y, x, m, y) Locks.t ->
    (x, b, y, x, m, y) Locks.t =
 fun p n i l ->
  match (i, l) with
  | Now, _ -> Suc (l, Locks_dim (p, n), Zero)
  | Later i, Suc (l, Locks_dim (p', n'), Zero) ->
      Suc (insert_locks p n i l, Locks_dim (p', n'), Zero)

(* Two successive insertions can be performed in the other order. *)
type (_, _, _, _, _, _) comp_insert =
  | Comp_insert :
      ('a, 'y, 'k, 'd) insert * ('d, 'x, 'n, 'c) insert
      -> ('a, 'x, 'n, 'y, 'k, 'c) comp_insert

let rec comp_insert : type a x n y k b c.
    (a, x, n, b) insert -> (b, y, k, c) insert -> (a, x, n, y, k, c) comp_insert =
 fun ab bc ->
  match (ab, bc) with
  | Now, Now -> Comp_insert (Now, Later Now)
  | Now, Later bc -> Comp_insert (bc, Now)
  | Later ab, Now -> Comp_insert (Now, Later (Later ab))
  | Later ab, Later bc ->
      let (Comp_insert (ad, dc)) = comp_insert ab bc in
      Comp_insert (Later ad, Later dc)

let rec int_of_insert : type a modality n b. (a, modality, n, b) insert -> int = function
  | Now -> 0
  | Later i -> 1 + int_of_insert i

type (_, _) permute =
  | Id : ('a, 'a) permute
  | Insert :
      ('a, 'b) permute * ('b, 'x, 'n, 'c) insert
      -> (('a, ('x, 'n) dim_entry) snoc, 'c) permute
  | Lock : ('a, 'b) permute -> (('a, 'n lock_entry) snoc, ('b, 'n lock_entry) snoc) permute

let id_perm : type a. (a, a) permute = Id

let rec perm_dom : type mode a b. (a, b) permute -> (mode, b) Tctx.t -> (mode, a) Tctx.t =
 fun p b ->
  match p with
  | Id -> b
  | Insert (p, i) ->
      let c = insert_dom i b in
      let a = perm_dom p c in
      let Wrap modality, n = inserted i b in
      Tctx.suc a (Dim (modality, n))
  | Lock p ->
      let (Path (Suc (b, Lock l), mode)) = b in
      Tctx.suc (perm_dom p (Path (b, mode))) (Lock l)

(* Insertions can be transferred across a permutation, and when the image is removed produce a new permutation. *)
type (_, _, _, _) permute_insert =
  | Permute_insert : ('d, 'x, 'n, 'c) insert * ('a, 'd) permute -> ('a, 'x, 'n, 'c) permute_insert

let rec permute_insert : type a x n b c.
    (a, x, n, b) insert -> (b, c) permute -> (a, x, n, c) permute_insert =
 fun ab bc ->
  match bc with
  | Id -> Permute_insert (ab, Id)
  | Insert (bc, ins) -> (
      match ab with
      | Now -> Permute_insert (ins, bc)
      | Later ab ->
          let (Permute_insert (res, p)) = permute_insert ab bc in
          let (Comp_insert (x, y)) = comp_insert res ins in
          Permute_insert (y, Insert (p, x)))
  | Lock _ -> (
      match ab with
      | _ -> .)

(* Compose a permutation with any tctx on the right. *)
let rec perm_comp : type a b c m n p mp np.
    (a, p, b, m, c, mp) comp -> (a, p, b, n, c, np) comp -> (m, n) permute -> (mp, np) permute =
 fun mp np mn ->
  match (mp, np) with
  | Zero, Zero -> mn
  | Suc (mp, g1), Suc (np, g2) -> (
      let Eq, Eq = (TEntry.src_uniq g1 g2, TEntry.tgt_uniq g1 g2) in
      let mnp = perm_comp mp np mn in
      match (g1, g2) with
      | Dim (_, _), Dim (_, _) -> Insert (mnp, Now)
      | Lock _, Lock _ -> Lock mnp
      | Proj _, Proj _ -> raise (Failure "perm_comp on Proj"))

let rec perm_bcomp : type a b c m n p mp np.
    (a, p, b, m, c, mp) bcomp -> (a, p, b, n, c, np) bcomp -> (m, n) permute -> (mp, np) permute =
 fun mp np mn ->
  match (mp, np) with
  | Zero, Zero -> mn
  | ( Suc (type b1 g) ((g1, mp) : (b1, g, b) TEntry.t * _),
      Suc (type b1') ((g2, np) : (b1', g, b) TEntry.t * _) ) -> (
      let Eq, Eq = (TEntry.src_uniq g1 g2, TEntry.tgt_uniq g1 g2) in
      match g1 with
      | Dim _ -> perm_bcomp mp np (Insert (mn, Now))
      | Lock _ -> perm_bcomp mp np (Lock mn)
      | Proj _ -> failwith "perm_bcomp: Proj")

(* And, dually, strip a lock on the right off of any permutation. *)
let rec perm_unlock : type a b c m n p mp np modality.
    (a, modality, b, a, p, b) Lock.t ->
    (a, p, b, m, c, mp) comp ->
    (a, p, b, n, c, np) comp ->
    (mp, np) permute ->
    (m, n) permute =
 fun p mp np mn ->
  match (p, mp, np) with
  | Zero _, Zero, Zero -> mn
  | Suc (p, Lock_lock _, Suc (Zero, g0)), Suc (mp, g1), Suc (np, g2) -> (
      let Eq, Eq = (TEntry.tgt_uniq g0 g1, TEntry.tgt_uniq g1 g2) in
      match mn with
      | Id -> perm_unlock p mp np Id
      | Lock mn' -> perm_unlock p mp np mn')

type (_, _, _, _, _, _) perm_unlock_dom =
  | Perm_unlock_dom :
      ('a, 'p, 'b, 'n, 'c, 'np) comp * ('m, 'n) permute
      -> ('a, 'p, 'b, 'c, 'm, 'np) perm_unlock_dom

let rec perm_unlock_dom : type a b c m p mp np modality.
    (a, modality, b, a, p, b) Lock.t ->
    (a, p, b, m, c, mp) comp ->
    (mp, np) permute ->
    (a, p, b, c, m, np) perm_unlock_dom =
 fun p mp mn ->
  match (p, mp) with
  | Zero _, Zero -> Perm_unlock_dom (Zero, mn)
  | Suc (p, Lock_lock _, Suc (Zero, g0)), Suc (mp, g1) -> (
      let Eq = TEntry.tgt_uniq g0 g1 in
      match mn with
      | Id ->
          let (Perm_unlock_dom (np, mn)) = perm_unlock_dom p mp Id in
          Perm_unlock_dom (Suc (np, g0), mn)
      | Lock mn' ->
          let (Perm_unlock_dom (np, mn)) = perm_unlock_dom p mp mn' in
          Perm_unlock_dom (Suc (np, g0), mn))

type (_, _, _, _, _, _) perm_unlock_cod =
  | Perm_unlock_cod :
      ('a, 'p, 'b, 'm, 'c, 'mp) comp * ('m, 'n) permute
      -> ('a, 'p, 'b, 'n, 'c, 'mp) perm_unlock_cod

let rec perm_unlock_cod : type a b c n p mp np modality.
    (a, modality, b, a, p, b) Lock.t ->
    (a, p, b, n, c, np) comp ->
    (mp, np) permute ->
    (a, p, b, n, c, mp) perm_unlock_cod =
 fun p np mn ->
  match (p, np) with
  | Zero _, Zero -> Perm_unlock_cod (Zero, mn)
  | Suc (p, Lock_lock _, Suc (Zero, g0)), Suc (np, g2) -> (
      let Eq = TEntry.tgt_uniq g0 g2 in
      match mn with
      | Insert (_, _) -> .
      | Id ->
          let (Perm_unlock_cod (mp, mn)) = perm_unlock_cod p np Id in
          Perm_unlock_cod (Suc (mp, g0), mn)
      | Lock mn' ->
          let (Perm_unlock_cod (mp, mn)) = perm_unlock_cod p np mn' in
          Perm_unlock_cod (Suc (mp, g0), mn))

(* Compose two permutations. *)
let rec comp_perm : type a b c. (a, b) permute -> (b, c) permute -> (a, c) permute =
 fun ab bc ->
  match ab with
  | Id -> bc
  | Insert (ab, b) ->
      let (Permute_insert (c, bc)) = permute_insert b bc in
      Insert (comp_perm ab bc, c)
  | Lock ab -> (
      match bc with
      | Id -> Lock ab
      | Lock bc -> Lock (comp_perm ab bc))

let rec coinsert : type a b m n c.
    (a, b) permute -> (a, m, n, c) insert -> (c, (b, (m, n) dim_entry) snoc) permute =
 fun p i ->
  match i with
  | Now -> Insert (p, Now)
  | Later i -> (
      match p with
      | Insert (p, j) -> Insert (coinsert p i, Later j)
      | Id -> (
          match i with
          | Now -> Insert (coinsert Id i, Later Now)
          | Later _ -> Insert (coinsert Id i, Later Now)))

let rec inv_perm : type a b. (a, b) permute -> (b, a) permute = function
  | Id -> Id
  | Insert (p, i) -> coinsert (inv_perm p) i
  | Lock p -> Lock (inv_perm p)

(* Backwards and forwards permutations *)

type (_, _, _, _, _) fwd_insert =
  | Now :
      ('u, 'x, 'mode) Modality.t * 'n D.t
      -> ('a, 'x, 'n, (('x, 'n) dim_entry, 'a) cons, 'mode) fwd_insert
  | Later :
      ('u, 'y, 'mode) Modality.t * ('a, 'x, 'n, 'b, 'mode) fwd_insert
      -> ((('y, 'k) dim_entry, 'a) cons, 'x, 'n, (('y, 'k) dim_entry, 'b) cons, 'mode) fwd_insert

let rec fwd_insert_cod : type u v a x n b.
    (a, x, n, b, v) fwd_insert -> (u, a, v) fwd -> (u, b, v) fwd =
 fun i a ->
  match i with
  | Now (x, n) -> Cons (Dim (x, n), a)
  | Later (y, i) ->
      let (Cons (Dim (k, n), a)) = a in
      let Eq = Modality.tgt_uniq y k in
      Cons (Dim (k, n), fwd_insert_cod i a)

type (_, _, _, _, _, _) bcomp_fwd_inserted =
  | Bcomp_fwd_inserted :
      ('x, 'd, 'y, 'a, 'z, 'ad) bcomp * ('ad, 'cb) permute
      -> ('x, 'd, 'y, 'a, 'z, 'cb) bcomp_fwd_inserted

let rec bcomp_fwd_inserted : type x y z a b c cb d m n.
    (x, b, y, c, z, cb) bcomp ->
    (a, m, n, c) insert ->
    (b, m, n, d, y) fwd_insert ->
    (x, d, y, a, z, cb) bcomp_fwd_inserted =
 fun cb bins fins ->
  match fins with
  | Now (m, n) ->
      let (Bcomp ad) = bcomp (bcomp_right cb) in
      Bcomp_fwd_inserted (Suc (Dim (m, n), ad), perm_bcomp ad cb (Insert (Id, bins)))
  | Later (m1, fins) ->
      let (Suc (Dim (m2, n), cb)) = cb in
      let Eq = Modality.tgt_uniq m1 m2 in
      let (Bcomp_fwd_inserted (ad, p)) = bcomp_fwd_inserted cb (Later bins) fins in
      Bcomp_fwd_inserted (Suc (Dim (m2, n), ad), p)

(* ('x, 'b, 'y, 'a, 'z, 'ab) bcomp_permute says that the backwards 'ab : 'x -> 'z is obtained from the backwards 'a : 'y -> 'z by composing with a permutation of the forwards 'b : 'x -> 'y. *)
type (_, _, _, _, _, _) bcomp_permute =
  | Id : ('x, 'n, 'y, 'm, 'z, 'mn) bcomp -> ('x, 'n, 'y, 'm, 'z, 'mn) bcomp_permute
  | Insert :
      ('b, 'annote, 'n, 'd, 'y) fwd_insert
      * ('x, 'b, 'y, ('a, ('annote, 'n) dim_entry) snoc, 'z, 'c) bcomp_permute
      -> ('x, 'd, 'y, 'a, 'z, 'c) bcomp_permute
  | Lock :
      ('y1, 'modality, 'y2) Modality.gen
      * ('x, 'b, 'y1, ('a, 'modality lock_entry) snoc, 'z, 'c) bcomp_permute
      -> ('x, ('modality lock_entry, 'b) cons, 'y2, 'a, 'z, 'c) bcomp_permute

let rec bcomp_permute_right : type x n y m z mn. (x, n, y, m, z, mn) bcomp_permute -> (x, n, y) fwd
    = function
  | Id b -> bcomp_right b
  | Insert (i, b) -> fwd_insert_cod i (bcomp_permute_right b)
  | Lock (m, b) -> Cons (Lock m, bcomp_permute_right b)

type (_, _, _, _, _, _) bcomp_bcomp_permute =
  | Bcomp_bcomp_permute :
      ('x, 'b, 'y, 'a, 'z, 'c) bcomp * ('d, 'c) permute
      -> ('x, 'b, 'y, 'a, 'z, 'd) bcomp_bcomp_permute

let rec bcomp_bcomp_permute : type a b d x y z.
    (x, b, y, a, z, d) bcomp_permute -> (x, b, y, a, z, d) bcomp_bcomp_permute =
 fun d ->
  match d with
  | Id d -> Bcomp_bcomp_permute (d, Id)
  | Insert (ins, d) ->
      let (Bcomp_bcomp_permute (b, p)) = bcomp_bcomp_permute d in
      let (Bcomp_fwd_inserted (b, q)) = bcomp_fwd_inserted b Now ins in
      Bcomp_bcomp_permute (b, comp_perm p (inv_perm q))
  | Lock (m, d) ->
      let (Bcomp_bcomp_permute (b, p)) = bcomp_bcomp_permute d in
      Bcomp_bcomp_permute (Suc (Lock m, b), p)

let permute_bcomp_permute : type a b c d x y z.
    (x, b, y, a, z, d) bcomp_permute -> (x, b, y, a, z, c) bcomp -> (d, c) permute =
 fun d c ->
  let (Bcomp_bcomp_permute (c', p)) = bcomp_bcomp_permute d in
  let Eq = bcomp_uniq c c' in
  p

(* Relating permutations to plus_lock. *)

type (_, _, _, _, _) permute_plus_lock =
  | Permute :
      ('am, 'bm) permute * ('a, 'mode, 'modality, 'dom, 'am) plus_lock
      -> ('a, 'mode, 'modality, 'dom, 'bm) permute_plus_lock

let permute_plus_lock : type a b mode modality dom bm.
    (a, b) permute ->
    (b, mode, modality, dom, bm) plus_lock ->
    (a, mode, modality, dom, bm) permute_plus_lock =
 fun perm (Plus_lock (lock, bcomp)) ->
  let (Comp acomp) = Tctx.comp (Lock.cod lock) in
  let mperm = perm_comp acomp bcomp perm in
  Permute (mperm, Plus_lock (lock, acomp))

type (_, _, _, _, _) unpermute_plus_lock =
  | Unpermute :
      ('a, 'b) permute * ('b, 'mode, 'modality, 'dom, 'bm) plus_lock
      -> ('a, 'mode, 'modality, 'dom, 'bm) unpermute_plus_lock

let unpermute_plus_lock : type a am bm mode modality dom.
    (am, bm) permute ->
    (a, mode, modality, dom, am) plus_lock ->
    (a, mode, modality, dom, bm) unpermute_plus_lock =
 fun permlock (Plus_lock (lock, acomp)) ->
  let (Perm_unlock_dom (bcomp, perm)) = perm_unlock_dom lock acomp permlock in
  Unpermute (perm, Plus_lock (lock, bcomp))

type (_, _, _, _, _) counpermute_plus_lock =
  | Counpermute :
      ('a, 'b) permute * ('a, 'mode, 'modality, 'dom, 'am) plus_lock
      -> ('b, 'mode, 'modality, 'dom, 'am) counpermute_plus_lock

let counpermute_plus_lock : type b am bm mode modality dom.
    (am, bm) permute ->
    (b, mode, modality, dom, bm) plus_lock ->
    (b, mode, modality, dom, am) counpermute_plus_lock =
 fun permlock (Plus_lock (lock, bcomp)) ->
  let (Perm_unlock_cod (acomp, perm)) = perm_unlock_cod lock bcomp permlock in
  Counpermute (perm, Plus_lock (lock, acomp))

(* And to Locks.  In order to ensure that a permutation decomposes along a composite, we require that the right factor in the composite starts with a lock. *)

type (_, _, _, _, _, _, _) unpermute_plus_locks =
  | Unpermute :
      ('a, 'b) permute
      * ('d, 'p) starts_with_lock_or_empty
      * ('dom, 'd, 'mode, 'b, unit, 'bd) Tctx.comp
      * ('dom, 'd, 'mode, 'dom, 'mu, 'mode) Locks.t
      -> ('a, 'dom, 'mu, 'mode, 'c, 'bd, 'p) unpermute_plus_locks

let rec unpermute_plus_locks : type a c ac bd mode mu dom p.
    (ac, bd) permute ->
    (c, p) starts_with_lock_or_empty ->
    (dom, c, mode, a, unit, ac) Tctx.comp ->
    (dom, c, mode, dom, mu, mode) Locks.t ->
    (a, dom, mu, mode, c, bd, p) unpermute_plus_locks =
 fun p c ac lc ->
  match (p, c, ac, lc) with
  | _, _, Zero, Zero x -> Unpermute (p, c, Zero, Zero x)
  | Id, _, _, _ -> Unpermute (Id, c, ac, lc)
  | Insert (p, i), Starts (Suc c), Suc (ac, Dim (m, k)), Suc (lc, Locks_dim (_, _), Zero) ->
      let (Unpermute (p, Starts d, bd, ld)) = unpermute_plus_locks p (Starts c) ac lc in
      let (Insert_from_comp (bd, d, j)) = insert_from_comp m k i bd d in
      let ld = insert_locks m k j ld in
      Unpermute (p, Starts d, bd, ld)
  | Lock p, Starts (Suc c), Suc (ac, Lock g), Suc (lc, Locks_lock g', Suc (Zero, _)) ->
      let Eq = Modality.Gen.tgt_uniq g g' in
      let (Unpermute (p, Starts d, bd, ld)) = unpermute_plus_locks p (Starts c) ac lc in
      Unpermute (p, Starts (Suc d), Suc (bd, Lock g), Suc (ld, Locks_lock g, Suc (Zero, g)))
  | Lock p, Starts Lock, Suc (Zero, Lock g), Suc (Zero _, Locks_lock _, Suc (Zero, _)) ->
      Unpermute (p, Starts Lock, Suc (Zero, Lock g), lc)

(* Variable indices.  Since we have keys that strip off part of the context and apply a cell, it may seem that as actual variables we only need the "zero variable" that's locked with the same modality it is annotated with, as in the MTT paper.  This isn't quite right, though, because environments can be permuted, and to find the zero variable in a permuted environment we need to look through the unpermuted environment for a non-zero variable.  Thus, we label variables by an insertion (which, recall, can only permute variables, not locks).  However, we do require that the variable's annotation is the same as the composite of all the locks to its right.  Finally, we also include a face to select one of a cube of variables. *)

type (_, _) index =
  | Index :
      ('a, 'modality, 'n, 'an) insert
      * ('k, 'n) sface
      * ('an, 'mode, 'modality, 'dom, 'anm) plus_lock
      -> ('dom, 'anm) index

let permute_index : type anm bnm mode. (anm, bnm) permute -> (mode, anm) index -> (mode, bnm) index
    =
 fun permlock (Index (ia, fa, am)) ->
  let (Unpermute (perm, bm)) = unpermute_plus_lock permlock am in
  let (Permute_insert (ib, _)) = permute_insert ia perm in
  Index (ib, fa, bm)

(* Add the same dimension on the left of all the dimensions in a type-level context. *)

module Anyplus = struct
  module Param = D
  module Dom = TEntry
  module Cod = TEntry

  module Obj = struct
    module Param = Param
    module Dom = ModeUnit
    module Cod = ModeUnit

    type (_, _, _) t = Eq : 'a ModeUnit.t -> ('p, 'a, 'a) t

    let dom : type p a x. (p, a, x) t -> a Dom.t = fun (Eq a) -> a
    let cod : type p a x. p Param.t -> (p, a, x) t -> x Cod.t = fun _ (Eq a) -> a

    type (_, _) exists = Exists : ('p, 'a, 'x) t -> ('p, 'a) exists

    let exists : type p a. p Param.t -> a Dom.t -> (p, a) exists = fun _ a -> Exists (Eq a)

    let uniq : type p a x1 x2. (p, a, x1) t -> (p, a, x2) t -> (x1, x2) Eq.t =
     fun x1 x2 ->
      match (x1, x2) with
      | Eq _, Eq _ -> Eq
  end

  type (_, _, _, _, _, _, _) t =
    | Plus_dim :
        ('dom, 'modality, 'mode) Modality.t * ('p, 'n, 'pn) D.plus
        -> ('p, 'mode, ('modality, 'n) dim_entry, 'mode, 'mode, ('modality, 'pn) dim_entry, 'mode) t
    | Plus_lock :
        ('dom, 'mu, 'cod) Modality.gen
        -> ('p, 'dom, 'mu lock_entry, 'cod, 'dom, 'mu lock_entry, 'cod) t
    | Plus_proj : 'mode Mode.t -> ('p, 'mode, 'mode proj, unit, 'mode, 'mode proj, unit) t

  let dom : type param a m b x n y. (param, a, m, b, x, n, y) t -> (a, m, b) Dom.t = function
    | Plus_dim (x, a) -> Dim (x, D.plus_right a)
    | Plus_lock m -> Lock m
    | Plus_proj x -> Proj x

  let cod : type param a m b x n y. param Param.t -> (param, a, m, b, x, n, y) t -> (x, n, y) Cod.t
      =
   fun p -> function
    | Plus_dim (x, a) -> Dim (x, D.plus_out p a)
    | Plus_lock m -> Lock m
    | Plus_proj x -> Proj x

  let src : type param a m b x n y. (param, a, m, b, x, n, y) t -> (param, a, x) Obj.t = function
    | Plus_dim (x, _) -> Eq (Mode (Modality.tgt x))
    | Plus_lock m -> Eq (Mode (Modality.Gen.src m))
    | Plus_proj x -> Eq (Mode x)

  let tgt : type param a m b x n y. (param, a, m, b, x, n, y) t -> (param, b, y) Obj.t = function
    | Plus_dim (x, _) -> Eq (Mode (Modality.tgt x))
    | Plus_lock m -> Eq (Mode (Modality.Gen.tgt m))
    | Plus_proj _ -> Eq Unit

  type (_, _, _, _) exists =
    | Exists : ('param, 'a, 'm, 'b, 'x, 'n, 'y) t -> ('param, 'a, 'm, 'b) exists

  let exists : type param a m b. param Param.t -> (a, m, b) Dom.t -> (param, a, m, b) exists =
   fun _ -> function
    | Dim (x, a) ->
        let (Plus pa) = D.plus a in
        Exists (Plus_dim (x, pa))
    | Lock m -> Exists (Plus_lock m)
    | Proj x -> Exists (Plus_proj x)

  let uniq : type param a m b x1 n1 y1 x2 n2 y2.
      (param, a, m, b, x1, n1, y1) t ->
      (param, a, m, b, x2, n2, y2) t ->
      (x1 * n1 * y1, x2 * n2 * y2) Eq.t =
   fun f1 f2 ->
    match (f1, f2) with
    | Plus_dim (_, n1), Plus_dim (_, n2) ->
        let Eq = D.plus_uniq n1 n2 in
        Eq
    | Plus_lock _, Plus_lock _ -> Eq
    | Plus_proj _, Plus_proj _ -> Eq
end

module Plusmap = struct
  include Path.Fmap (TEntry) (TEntry) (Anyplus)

  let rec assocl : type a b ab cs bcs abcs x y.
      (a, b, ab) D.plus ->
      (b, x, cs, y, x, bcs, y) t ->
      (a, x, bcs, y, x, abcs, y) t ->
      (ab, x, cs, y, x, abcs, y) t =
   fun ab bcs abcs ->
    match (bcs, abcs) with
    | Zero (Eq mode), Zero _ -> Zero (Eq mode)
    | ( Suc (bcs, Inject (Plus_dim (x, bc)), Suc (Zero, _)),
        Suc (abcs, Inject (Plus_dim (_, a_bc)), Suc (Zero, Dim (_, abc'))) ) ->
        let ab_c = D.plus_assocl ab bc a_bc in
        Suc (assocl ab bcs abcs, Inject (Plus_dim (x, ab_c)), Suc (Zero, Dim (x, abc')))
    | ( Suc (bcs, Inject (Plus_lock m), Suc (Zero, m')),
        Suc (abcs, Inject (Plus_lock n), Suc (Zero, _)) ) ->
        let Eq = Modality.Gen.tgt_uniq m n in
        Suc (assocl ab bcs abcs, Inject (Plus_lock m), Suc (Zero, m'))
    | Suc (Zero _, Inject (Plus_proj x), Suc _), Suc (Zero _, Inject (Plus_proj _), Suc (Zero, _))
      -> Suc (Zero (Eq Unit), Inject (Plus_proj x), Suc (Zero, Proj x))
    (* Now a bunch of impossible cases *)
    | Suc (Zero _, Inject (Plus_proj _), _), Suc (_, Inject (Plus_dim _), _) -> .
    | Suc (Zero _, Inject (Plus_proj _), _), Suc (_, Inject (Plus_lock _), _) -> .
    | Suc (Zero _, Inject (Plus_proj _), _), Zero _ -> .
    | Suc (Suc (_, _, _), Inject (Plus_proj _), _), Zero _ -> .
    | Suc (Suc (_, _, _), Inject (Plus_proj _), _), Suc (_, Inject (Plus_dim (_, _)), _) -> .
    | Suc (Suc (_, _, _), Inject (Plus_proj _), _), Suc (_, Inject (Plus_lock _), _) -> .
    (* And now a bunch of cases that are also impossible, but OCaml can't tell that without help since Mode.t is abstract here so it doesn't know that unit is not a mode.  *)
    | ( Suc (Suc (_, Inject (Plus_dim (modality, _)), _), Inject (Plus_proj _), _),
        Suc (_, Inject (Plus_proj _), _) ) -> Mode.not_unit (Modality.tgt modality) Eq
    | ( Suc (Suc (_, Inject (Plus_lock modality), _), Inject (Plus_proj _), _),
        Suc (_, Inject (Plus_proj _), _) ) -> Mode.not_unit (Modality.Gen.src modality) Eq
    | ( Suc (Suc (_, Inject (Plus_proj mode), _), Inject (Plus_proj _), _),
        Suc (_, Inject (Plus_proj _), _) ) -> Mode.not_unit mode Eq
    | ( Suc (_, Inject (Plus_proj _), _),
        Suc (Suc (_, Inject (Plus_dim (modality, _)), _), Inject (Plus_proj _), _) ) ->
        Mode.not_unit (Modality.tgt modality) Eq
    | ( Suc (_, Inject (Plus_proj _), _),
        Suc (Suc (_, Inject (Plus_lock modality), _), Inject (Plus_proj _), _) ) ->
        Mode.not_unit (Modality.Gen.src modality) Eq
    | ( Suc (_, Inject (Plus_proj _), _),
        Suc (Suc (_, Inject (Plus_proj mode), _), Inject (Plus_proj _), _) ) ->
        Mode.not_unit mode Eq

  let rec zerol : type x bs y. (x, bs, y) Dom.t -> (D.zero, x, bs, y, x, bs, y) t = function
    | Path (Zero, mode) -> Zero (Eq mode)
    | Path (Suc (bs, Dim (x, b)), mode) ->
        Suc (zerol (Path (bs, mode)), Inject (Plus_dim (x, D.zero_plus b)), Suc (Zero, Dim (x, b)))
    | Path (Suc (bs, Lock m), mode) ->
        Suc (zerol (Path (bs, mode)), Inject (Plus_lock m), Suc (Zero, Lock m))
    | Path (Suc (Zero, Proj x), _) -> Suc (Zero (Eq Unit), Inject (Plus_proj x), Suc (Zero, Proj x))
    (* Again, we have some manually-proven impossible cases *)
    | Path (Suc (Suc (_, Dim (modality, _)), Proj _), _) -> Mode.not_unit (Modality.tgt modality) Eq
    | Path (Suc (Suc (_, Lock modality), Proj _), _) -> Mode.not_unit (Modality.Gen.src modality) Eq
    | Path (Suc (Suc (_, Proj mode), Proj _), _) -> Mode.not_unit mode Eq

  (* Adding a dimension acts as the identity on pure locks. *)
  let rec lock : type a x m y l. (x, m, y, x, l, y) Lock.t -> (a, x, l, y, x, l, y) t = function
    | Zero (Eq mode) -> Zero (Eq (Mode mode))
    | Suc (ml, Lock_lock m, Suc (Zero, l)) -> Suc (lock ml, Inject (Plus_lock m), Suc (Zero, l))

  (* And it preserves the composite of locks *)
  let rec locks : type n x y b nb m.
      n D.t -> (n, x, b, y, x, nb, y) t -> (x, b, y, x, m, y) Locks.t -> (x, nb, y, x, m, y) Locks.t
      =
   fun n n_b ll_b ->
    match (n_b, ll_b) with
    | Zero _, Zero m -> Zero m
    | Suc (n_b, Inject (Plus_dim (mu, nm)), Suc (Zero, _)), Suc (ll_b, Locks_dim _, Zero) ->
        Suc (locks n n_b ll_b, Locks_dim (mu, D.plus_out n nm), Zero)
    | Suc (n_b, Inject (Plus_lock mu), Suc (Zero, _)), Suc (ll_b, Locks_lock mu', Suc (Zero, _)) ->
        let Eq = Modality.Gen.tgt_uniq mu mu' in
        Suc (locks n n_b ll_b, Locks_lock mu, Suc (Zero, mu))
    | Suc (_, Inject (Plus_proj _), _), Suc (_, _, _) -> .

  let rec unlocks : type n x y b nb m.
      (n, x, b, y, x, nb, y) t -> (x, nb, y, x, m, y) Locks.t -> (x, b, y, x, m, y) Locks.t =
   fun n_b ll_nb ->
    match (n_b, ll_nb) with
    | Zero _, Zero m -> Zero m
    | Suc (n_b, Inject (Plus_dim (mu, nm)), Suc (Zero, _)), Suc (ll_nb, Locks_dim _, Zero) ->
        Suc (unlocks n_b ll_nb, Locks_dim (mu, D.plus_right nm), Zero)
    | Suc (n_b, Inject (Plus_lock mu), Suc (Zero, _)), Suc (ll_nb, Locks_lock mu', Suc (Zero, _)) ->
        let Eq = Modality.Gen.tgt_uniq mu mu' in
        Suc (unlocks n_b ll_nb, Locks_lock mu, Suc (Zero, mu))
    | Suc (_, Inject (Plus_lock _), _), Suc (_, Locks_dim (_, _), _) -> .
    | Suc (_, Inject (Plus_dim (_, _)), _), Suc (_, Locks_lock _, _) -> .
    | Suc (_, Inject (Plus_proj _), _), Suc (_, _, _) -> .
    | Suc (_, _, _), Zero _ -> .

  let rec cod_starts_with_lock : type n x a y na.
      (n, x, a, y, x, na, y) t -> a starts_with_lock -> na starts_with_lock =
   fun na -> function
    | Lock ->
        let (Suc (Zero _, Inject (Plus_lock _), Suc (Zero, _))) = na in
        Lock
    | Suc s ->
        let (Suc (na, Inject _, Suc (Zero, _))) = na in
        let (Eq _) = src na in
        Suc (cod_starts_with_lock na s)

  let cod_starts_with_lock_or_empty : type n x a y na p.
      (n, x, a, y, x, na, y) t ->
      (a, p) starts_with_lock_or_empty ->
      (na, p) starts_with_lock_or_empty =
   fun na -> function
    | Starts s -> Starts (cod_starts_with_lock na s)
    | Empty ->
        let (Zero _) = na in
        Empty

  let rec dom_starts_with_lock : type n x a y na.
      (n, x, a, y, x, na, y) t -> na starts_with_lock -> a starts_with_lock =
   fun na -> function
    | Lock -> (
        match na with
        | Suc (Zero _, Inject (Plus_lock _), Suc (Zero, Lock _)) -> Lock
        | Suc (Zero _, Inject (Plus_dim _), _) -> .
        | Suc (Zero _, Inject (Plus_proj _), _) -> .
        | Suc (Suc (_, _, Zero), Inject _, _) -> .
        | Suc (Suc (_, Inject _, Suc (_, _)), Inject _, Suc (_, _)) -> .)
    | Suc s ->
        let (Suc (na, Inject _, Suc (Zero, _))) = na in
        let (Eq _) = src na in
        Suc (dom_starts_with_lock na s)

  let dom_starts_with_lock_or_empty : type n x a y na p.
      (n, x, a, y, x, na, y) t ->
      (na, p) starts_with_lock_or_empty ->
      (a, p) starts_with_lock_or_empty =
   fun na -> function
    | Starts s -> Starts (dom_starts_with_lock na s)
    | Empty ->
        let (Zero _) = na in
        Empty

  type (_, _, _, _, _, _, _) uninsert =
    | Uninsert :
        ('p, 'x, 'fx) D.plus * ('zs, 'm, 'fx, 'ws) insert * ('p, 'a, 'xs, 'b, 'a, 'zs, 'b) t
        -> ('p, 'x, 'm, 'a, 'xs, 'b, 'ws) uninsert

  let rec uninsert : type p a b m xs x ys ws.
      (xs, m, x, ys) insert -> (p, a, ys, b, a, ws, b) t -> (p, x, m, a, xs, b, ws) uninsert =
   fun i fxs ->
    match (fxs, i) with
    | Suc (fxs, Inject (Plus_dim (_, fx)), Suc (Zero, _)), Now -> Uninsert (fx, Now, fxs)
    | Suc (fxs, Inject (Plus_dim (m, fx)), Suc (Zero, yy)), Later i ->
        let (Uninsert (u, fi, fxs)) = uninsert i fxs in
        Uninsert (u, Later fi, Suc (fxs, Inject (Plus_dim (m, fx)), Suc (Zero, yy)))
    | Suc (_, Inject (Plus_lock _), Suc (Zero, _)), _ -> .
    | Suc (_, Inject (Plus_proj _), Suc (Zero, _)), _ -> .
    | Zero _, _ -> .

  type (_, _, _, _, _, _, _) uncoinsert =
    | Uncoinsert :
        ('p, 'x, 'z) D.plus * ('xs, 'm, 'x, 'ys) insert * ('p, 'a, 'xs, 'b, 'a, 'zs, 'b) t
        -> ('p, 'z, 'm, 'a, 'ys, 'b, 'zs) uncoinsert

  let rec uncoinsert : type p a b m ys z zs ws.
      (zs, m, z, ws) insert -> (p, a, ys, b, a, ws, b) t -> (p, z, m, a, ys, b, zs) uncoinsert =
   fun i fxs ->
    match i with
    | Now ->
        let (Suc (fxs, Inject (Plus_dim (_, fx)), Suc (Zero, _))) = fxs in
        Uncoinsert (fx, Now, fxs)
    | Later i ->
        let (Suc (fxs, Inject (Plus_dim (m, fx)), Suc (Zero, yy))) = fxs in
        let (Uncoinsert (fx', fi, fxs)) = uncoinsert i fxs in
        Uncoinsert (fx', Later fi, Suc (fxs, Inject (Plus_dim (m, fx)), Suc (Zero, yy)))
end

(* Four helper functions for commuting plus_lock with Plusmap.  Yes, all four are really different.  Suggestions of better names for them are welcome. *)

type (_, _, _, _, _, _) shift_plus_lock =
  | Shift :
      ('n, 'mode, 'b, unit, 'mode, 'nb, unit) Plusmap.t * ('b, 'mode, 'k, 'dom, 'bk) plus_lock
      -> ('n, 'dom, 'k, 'mode, 'nb, 'bk) shift_plus_lock

(* This is the odd one out of the four: it is a recursive definition that inspects the definitions rather than being just put together out of general properties of parametrized functors. *)
let rec shift_plus_lock : type n k nb bk nbk dom mode.
    n D.t ->
    (n, dom, bk, unit, dom, nbk, unit) Plusmap.t ->
    (nb, mode, k, dom, nbk) plus_lock ->
    (n, dom, k, mode, nb, bk) shift_plus_lock =
 fun n n_bk (Plus_lock (lk, nb_k)) ->
  match (lk, nb_k) with
  | Zero mode, Zero -> Shift (n_bk, Plus_lock (Zero mode, Zero))
  | Suc (lk, Lock_lock g1, Suc (Zero, Lock g2)), Suc (nb_k, Lock g3) ->
      let (Suc (n_bk, Inject (Plus_lock g4), Suc (Zero, Lock _))) = n_bk in
      let Eq = Modality.Gen.tgt_uniq g2 g3 in
      let Eq = Modality.Gen.tgt_uniq g3 g4 in
      let (Shift (nb, Plus_lock (lk', bk))) = shift_plus_lock n n_bk (Plus_lock (lk, nb_k)) in
      Shift (nb, Plus_lock (Suc (lk', Lock_lock g1, Suc (Zero, Lock g1)), Suc (bk, Lock g1)))

type (_, _, _, _, _, _) shift_unplus_lock =
  | Shift :
      ('n, 'dom, 'bk, unit, 'dom, 'nbk, unit) Plusmap.t * ('nb, 'mode, 'k, 'dom, 'nbk) plus_lock
      -> ('n, 'mode, 'k, 'dom, 'nb, 'bk) shift_unplus_lock

let shift_unplus_lock : type n b k nb bk dom mode.
    n D.t ->
    (n, mode, b, unit, mode, nb, unit) Plusmap.t ->
    (b, mode, k, dom, bk) plus_lock ->
    (n, mode, k, dom, nb, bk) shift_unplus_lock =
 fun n nb (Plus_lock (lk, bk)) ->
  let nk = Plusmap.lock lk in
  let (Comp (nbk, nb_nk)) = Plusmap.comp n nb nk bk in
  Shift (nbk, Plus_lock (lk, nb_nk))

type (_, _, _, _, _, _) unshift_plus_lock =
  | Unshift :
      ('n, 'mode, 'b, unit, 'mode, 'nb, unit) Plusmap.t * ('nb, 'mode, 'k, 'dom, 'nbk) plus_lock
      -> ('n, 'dom, 'k, 'mode, 'b, 'nbk) unshift_plus_lock

let unshift_plus_lock : type n b k bk nbk dom mode.
    n D.t ->
    (n, dom, bk, unit, dom, nbk, unit) Plusmap.t ->
    (b, mode, k, dom, bk) plus_lock ->
    (n, dom, k, mode, b, nbk) unshift_plus_lock =
 fun n n_bk (Plus_lock (lk, b_k)) ->
  let (Uncomp (nb, nk, nb_nk)) = Plusmap.uncomp n b_k n_bk in
  let (Eq _) = Plusmap.src nb in
  let Eq = Plusmap.uniq nk (Plusmap.lock lk) in
  Unshift (nb, Plus_lock (lk, nb_nk))

type (_, _, _, _, _, _) unshift_unplus_lock =
  | Unshift :
      ('n, 'dom, 'bk, unit, 'dom, 'nbk, unit) Plusmap.t * ('b, 'mode, 'k, 'dom, 'bk) plus_lock
      -> ('n, 'dom, 'b, 'k, 'nbk, 'mode) unshift_unplus_lock

let unshift_unplus_lock : type n b k nb nbk mode dom.
    n D.t ->
    (n, mode, b, unit, mode, nb, unit) Plusmap.t ->
    (nb, mode, k, dom, nbk) plus_lock ->
    (n, dom, b, k, nbk, mode) unshift_unplus_lock =
 fun n nb (Plus_lock (lk, nb_k)) ->
  let nk = Plusmap.lock lk in
  let (Comp bk) = comp (Lock.cod lk) in
  let (Comp (n_bk, nb_k')) = Plusmap.comp n nb nk bk in
  let Eq = Tctx.comp_uniq nb_k nb_k' in
  Unshift (n_bk, Plus_lock (lk, bk))

(* Now we wrap the plusmap types and functions to remove unnecessary parameters. *)

type ('n, 'a, 'an, 'mode) plusmap = ('n, 'mode, 'a, unit, 'mode, 'an, unit) Plusmap.t

type (_, _, _) plusmap_exists =
  | Exists : ('n, 'a, 'an, 'mode) plusmap -> ('n, 'a, 'mode) plusmap_exists

let plusmap_exists : type n a mode. n D.t -> (mode, a) Tctx.t -> (n, a, mode) plusmap_exists =
 fun n ctx ->
  let (Exists pm) = Plusmap.exists n ctx in
  let Eq _, Eq _ = (Plusmap.src pm, Plusmap.tgt pm) in
  Exists pm
