The -variables flag configures the names used for autogenerated variables.

  $ narya -variables a,b -e "def ℕ : Type ≔ data [ zero. | suc. (_ : ℕ) ] def kinetic_suc : ℕ → ℕ ≔ ((x : ℕ → ℕ) ↦ x : ℕ → ℕ) suc. echo kinetic_suc"
  a ↦ suc. a
    : ℕ → ℕ
  

If there are more autogenerated variables than supplied names, they are reused with primes.

  $ narya -variables v -e "def ℕ : Type ≔ data [ zero. | pair. (_ : ℕ) (_ : ℕ) ] def kinetic_pair : ℕ → ℕ → ℕ ≔ ((x : ℕ → ℕ → ℕ) ↦ x : ℕ → ℕ → ℕ) pair. echo kinetic_pair"
  v v′ ↦ pair. v v′
    : ℕ → ℕ → ℕ
  

The argument of -variables must be a nonempty comma-separated list of valid variable names.

  $ narya -variables "" -e "echo Type"
   ￫ error[E0202]
   ￮ invalid local variable name: 
  
  [1]

  $ narya -variables "a,,b" -e "echo Type"
   ￫ error[E0202]
   ￮ invalid local variable name: 
  
  [1]

  $ narya -variables "42" -e "echo Type"
   ￫ error[E0202]
   ￮ invalid local variable name: 42
  
  [1]

  $ narya -variables "a b" -e "echo Type"
   ￫ error[E0202]
   ￮ invalid local variable name: a b
  
  [1]

  $ narya -variables "a.b" -e "echo Type"
   ￫ error[E0202]
   ￮ invalid local variable name: a.b
  
  [1]

  $ narya -variables "let" -e "echo Type"
   ￫ error[E0202]
   ￮ invalid local variable name: let
  
  [1]

  $ narya -variables "_" -e "echo Type"
   ￫ error[E0202]
   ￮ invalid local variable name: _
  
  [1]

  $ narya -variables " a" -e "echo Type"
   ￫ error[E0202]
   ￮ invalid local variable name:  a
  
  [1]

  $ narya -variables "a," -e "echo Type"
   ￫ error[E0202]
   ￮ invalid local variable name: 
  
  [1]
