About: display the potential value (canonical type or case tree) of a neutral

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Stream : Type → Type ≔ A ↦ codata [ x .head : A | x .tail : Stream A ]' -e 'def R : Type ≔ sig ( a : Type, b : (a → Type) )' -e 'def pred : N → N ≔ [ zero. ↦ zero. | suc. n ↦ n ]' -e 'axiom ax : N' -e 'echo N' -e 'about N' -e 'about Stream' -e 'about R' -e 'about pred' -e 'about ax' -e 'about (pred (suc. zero.))'
  N
    : Type
  
  data [
  | zero.
  | suc. (𝑥 : N) ]
    : Type
  
  A ↦ codata [ 𝑥 .head : A | 𝑥 .tail : Stream A ]
    : Type → Type
  
  sig (
    𝑥 .a : Type,
    𝑥 .b : 𝑥 .a → Type )
    : Type
  
  𝑥 ↦ match 𝑥 [ suc. n ↦ n | zero. ↦ 0 ]
    : N → N
  
  ax
    : N
  
  0
    : N
  

A neutral that is an applied canonical type is read back and displayed as the corresponding declaration.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def List : Type → Type ≔ A ↦ data [ nil. | cons. (x : A) (xs : List A) ]' -e 'def Stream : Type → Type ≔ A ↦ codata [ x .head : A | x .tail : Stream A ]' -e 'def Vec : Type → N → Type ≔ A ↦ data [ nil. : Vec A zero. | cons. : (n : N) → A → Vec A n → Vec A (suc. n) ]' -e 'about (List N)' -e 'about (Stream N)' -e 'about (Vec N (suc. zero.))'
  data [
  | nil.
  | cons. (x : N) (xs : List N) ]
    : Type
  
  codata [
  | 𝑥 .head : N
  | 𝑥 .tail : Stream N ]
    : Type
  
  data [
  | nil. : Vec N 0
  | cons. (n : N) (𝑥 : N) (𝑦 : Vec N n) : Vec N (suc. n) ]
    : Type
  


"about" on a datatype constant itself (a parameter abstraction reaching a datatype) shows the parameters abstracted and the constructors' output types referring to the parameterized family.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Vec : Type → N → Type ≔ A ↦ data [ nil. : Vec A zero. | cons. : (n : N) → A → Vec A n → Vec A (suc. n) ]' -e 'about Vec'
  A ↦
  data [
  | nil. : Vec A 0
  | cons. (n : N) (𝑥 : A) (𝑦 : Vec A n) : Vec A (suc. n) ]
    : Type → N → Type
  


A higher-dimensional (Gel-like) codatatype is read back at its intrinsic dimension.

  $ narya -dtt -e 'axiom A : Type' -e 'axiom Aʹ : A → Type' -e 'def Gel (A : Type) (Aʹ : A → Type) : Type⁽ᵈ⁾ A ≔ sig x ↦ ( ungel : Aʹ x )' -e 'about (Gel A Aʹ)'
  sig (
    𝑥 .ungel : Aʹ 𝑥.0 )
    : Type⁽ᵈ⁾ A
  


A degenerate codatatype or record is read back at its full dimension, showing the in-practice (higher-dimensional) field types, including higher-pi field types with their boundary faces.

  $ narya -e 'axiom X : Type' -e 'def Stream : Type → Type ≔ A ↦ codata [ x .head : A | x .tail : Stream A ]' -e 'def R : Type ≔ sig ( a : Type, b : (a → Type) )' -e 'about (refl (Stream X))' -e 'about (refl R)'
  codata [
  | 𝑥 .head : Id X (𝑥.0 .head) (𝑥.1 .head)
  | 𝑥 .tail : Stream⁽ᵉ⁾ (Id X) (𝑥.0 .tail) (𝑥.1 .tail) ]
    : Type⁽ᵉ⁾ (Stream X) (Stream X)
  
  sig (
    𝑥 .a : Type⁽ᵉ⁾ (𝑥.0 .a) (𝑥.1 .a),
    𝑥 .b : {𝑥₀ : 𝑥.0 .a} {𝑥₁ : 𝑥.1 .a} (𝑥₂ : 𝑥.2 .a 𝑥₀ 𝑥₁)
           →⁽ᵉ⁾ Type⁽ᵉ⁾ (𝑥.0 .b 𝑥₀) (𝑥.1 .b 𝑥₁) )
    : Type⁽ᵉ⁾ R R
  


For a codatatype with a higher field, every instance of that field that a comatch would have to provide is listed: one per partial bijection between the codatatype's dimension and the field's intrinsic dimension.  This includes the projectable instances (.1, .2) as well as the non-projectable "declaration" instance (.e) and intermediate forms, the latter computed in a context degenerated by the remaining dimensions.  In particular, the undegenerate type reproduces the field's declaration.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def √N : Type ≔ codata [ x .root.e : N ]' -e 'about √N' -e 'about (refl √N)' -e 'about (refl (refl √N))'
  codata [
  | 𝑥 .root.e : N ]
    : Type
  
  codata [
  | 𝑥 .root.e : N⁽ᵉ⁾ (𝑥.02 .root) (𝑥.12 .root)
  | 𝑥 .root.1 : N ]
    : Type⁽ᵉ⁾ √N √N
  
  codata [
  | 𝑥 .root.e
    : N⁽ᵉᵉ⁾ (sym 𝑥.022 .root.1) (sym 𝑥.122 .root.1) (sym 𝑥.202 .root.1)
        (sym 𝑥.212 .root.1)
  | 𝑥 .root.1 : N⁽ᵉ⁾ (𝑥.20 .root) (𝑥.21 .root)
  | 𝑥 .root.2 : N⁽ᵉ⁾ (𝑥.02 .root) (𝑥.12 .root) ]
    : Type⁽ᵉᵉ⁾ √N⁽ᵉ⁾ √N⁽ᵉ⁾ √N⁽ᵉ⁾ √N⁽ᵉ⁾
  


A degenerate datatype is read back by reconstructing each constructor's higher-dimensional function-type: the constructor-as-a-function is degenerated, which instantiates the codomain at the lower-dimensional constructors (so e.g. cons. lands in List⁽ᵉ⁾ (Id X) (cons. x₀ xs₀) (cons. x₁ xs₁)).  This includes indexed datatypes, whose indices are degenerated as well (e.g. cons. lands in Vec⁽ᵉ⁾ (Id X) (suc. n₂) …).

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'axiom X : Type' -e 'def List : Type → Type ≔ A ↦ data [ nil. | cons. (x : A) (xs : List A) ]' -e 'def Vec : Type → N → Type ≔ A ↦ data [ nil. : Vec A zero. | cons. : (n : N) → A → Vec A n → Vec A (suc. n) ]' -e 'about (refl (List X))' -e 'about (refl N)' -e 'about (refl (Vec X zero.))'
  data [
  | nil. : List⁽ᵉ⁾ (Id X) nil. nil.
  | cons.
    : {x₀ : X} {x₁ : X} (x₂ : Id X x₀ x₁) {xs₀ : List X} {xs₁ : List X}
      (xs₂ : List⁽ᵉ⁾ (Id X) xs₀ xs₁)
      →⁽ᵉ⁾ List⁽ᵉ⁾ (Id X) (cons. x₀ xs₀) (cons. x₁ xs₁) ]
    : Type⁽ᵉ⁾ (List X) (List X)
  
  data [
  | zero. : N⁽ᵉ⁾ 0 0
  | suc. : {𝑥₀ : N} {𝑥₁ : N} (𝑥₂ : N⁽ᵉ⁾ 𝑥₀ 𝑥₁) →⁽ᵉ⁾ N⁽ᵉ⁾ (suc. 𝑥₀) (suc. 𝑥₁) ]
    : Type⁽ᵉ⁾ N N
  
  data [
  | nil. : Vec⁽ᵉ⁾ (Id X) {0} {0} (refl 0) nil. nil.
  | cons.
    : {n₀ : N} {n₁ : N} (n₂ : N⁽ᵉ⁾ n₀ n₁) {𝑥₀ : X} {𝑥₁ : X} (𝑥₂ : Id X 𝑥₀ 𝑥₁)
      {𝑦₀ : Vec X n₀} {𝑦₁ : Vec X n₁} (𝑦₂ : Vec⁽ᵉ⁾ (Id X) n₂ 𝑦₀ 𝑦₁)
      →⁽ᵉ⁾ Vec⁽ᵉ⁾ (Id X) {suc. n₀} {suc. n₁} (suc. n₂) (cons. n₀ 𝑥₀ 𝑦₀)
             (cons. n₁ 𝑥₁ 𝑦₁) ]
    : Type⁽ᵉ⁾ (Vec X 0) (Vec X 0)
  


In a parametricity configuration with no endpoints (arity 0), a degenerate datatype still displays: an arity-0 cube has no boundary face to recover the zero-dimensional datatype from, but each constructor's function type is read back directly in its degenerate environment.  There are no implicit boundary arguments, but there is still the (empty) instantiation, displayed as ".".

  $ narya -arity 0 -parametric -e 'axiom X : Type' -e 'def List : Type → Type ≔ A ↦ data [ nil. | cons. (x : A) (xs : List A) ]' -e 'about (List X)⁽ᵉ⁾'
  data [
  | nil. : List⁽ᵉ⁾ (Id X) .
  | cons. : (x₀ : Id X .) (xs₀ : List⁽ᵉ⁾ (Id X) .) →⁽ᵉ⁾ List⁽ᵉ⁾ (Id X) . ]
    : Type⁽ᵉ⁾ .
  


A datatype defined nested inside a case tree is reached through the tree rather than as a top-level canonical type, so "about" displays the stored case tree.  Each nested datatype's constructor output types are shown faithfully (with the real datatype head) from the stored output term.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def W (n : N) : N → Type ≔ match n [ zero. ↦ data [ w0. : W n zero. ] | suc. m ↦ data [ w1. : W n (suc. m) ] ]' -e 'about W'
  n ↦
  match n [
  | suc. m ↦ data [
    | w1. : W n (suc. m) ]
  | zero. ↦ data [
    | w0. : W n 0 ]]
    : (n : N) → N → Type
  


A neutral whose value is a comatch (a coinductive record without eta) is read back and displayed as that comatch, by projecting each field.  This includes comatches that are only partially applied, and hence are not stored case trees that could be displayed by name.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Stream : Type → Type ≔ A ↦ codata [ x .head : A | x .tail : Stream A ]' -e 'def s : Stream N ≔ [ .head ↦ 0 | .tail ↦ s ]' -e 'def const : (A : Type) → A → Stream A ≔ A a ↦ [ .head ↦ a | .tail ↦ const A a ]' -e 'about s' -e 'about (const N 0)'
  [ .head ↦ 0 | .tail ↦ s ]
    : Stream N
  
  [ .head ↦ 0 | .tail ↦ const N 0 ]
    : Stream N
  



A comatch against a codatatype with a higher field is read back by reading back each field instance's body: lower fields and projectable higher instances directly, non-projectable higher instances (like the declaration ".root.e") in a context degenerated by the partial bijection's remaining dimensions, evaluating the comatch's stored field term there.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def √N : Type ≔ codata [ x .root.e : N ]' -e 'def r : √N ≔ [ .root.e ↦ 0 ]' -e 'about r' -e 'about (refl r)'
  [ .root.e ↦ 0 ]
    : √N
  
  [ .root.e ↦ 0 ]
    : √N⁽ᵉ⁾ r r
  



A comatch can mix lower and higher fields; all are read back.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def C : Type ≔ codata [ x .head : N | x .root.e : N ]' -e 'def c : C ≔ [ .head ↦ 0 | .root.e ↦ suc. 0 ]' -e 'about c'
  [ .head ↦ 0 | .root.e ↦ 1 ]
    : C
  

















