About: display the potential value (canonical type or case tree) of a neutral

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Stream : Type → Type ≔ A ↦ codata [ x .head : A | x .tail : Stream A ]' -e 'def R : Type ≔ sig ( a : Type, b : (a → Type) )' -e 'def pred : N → N ≔ [ zero. ↦ zero. | suc. n ↦ n ]' -e 'axiom ax : N' -e 'echo N' -e 'about N' -e 'about Stream' -e 'about R' -e 'about pred' -e 'about ax' -e 'about (pred (suc. zero.))'
  N
    : Type
  
  data [
  | zero. : N
  | suc. (𝑥 : N) : N ]
    : Type
  
  A ↦ codata [ x .head : A | x .tail : Stream A ]
    : Type → Type
  
  sig (
    a : Type,
    b : a → Type )
    : Type
  
  𝑥 ↦ match 𝑥 [ suc. n ↦ n | zero. ↦ 0 ]
    : N → N
  
  ax
    : N
  
  0
    : N
  

A neutral that is an applied canonical type is read back and displayed as the corresponding declaration.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def List : Type → Type ≔ A ↦ data [ nil. | cons. (x : A) (xs : List A) ]' -e 'def Stream : Type → Type ≔ A ↦ codata [ x .head : A | x .tail : Stream A ]' -e 'def Vec : Type → N → Type ≔ A ↦ data [ nil. : Vec A zero. | cons. : (n : N) → A → Vec A n → Vec A (suc. n) ]' -e 'about (List N)' -e 'about (Stream N)' -e 'about (Vec N (suc. zero.))'
  data [
  | nil. : List N
  | cons. (x : N) (xs : List N) : List N ]
    : Type
  
  codata [
  | x .head : N
  | x .tail : Stream N ]
    : Type
  
  data [
  | nil. : Vec N 0
  | cons. (n : N) (𝑥 : N) (𝑦 : Vec N n) : Vec N (suc. n) ] 1
    : Type
  


"about" on a datatype constant itself (a parameter abstraction reaching a datatype) shows the parameters abstracted and the constructors' output types referring to the parameterized family.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Vec : Type → N → Type ≔ A ↦ data [ nil. : Vec A zero. | cons. : (n : N) → A → Vec A n → Vec A (suc. n) ]' -e 'about Vec'
  A ↦
  data [
  | nil. : Vec A 0
  | cons. (n : N) (𝑥 : A) (𝑦 : Vec A n) : Vec A (suc. n) ]
    : Type → N → Type
  


An indexed datatype that has been applied to its parameters but not yet to all of its indices is a canonical type whose *type* is a pi-type rather than a universe, the remaining indices being still to come.  It displays as the datatype declaration, with the indices supplied so far given as an application afterwards, just as for a fully applied one.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Vec : Type → N → Type ≔ A ↦ data [ nil. : Vec A zero. | cons. : (n : N) → A → Vec A n → Vec A (suc. n) ]' -e 'axiom X : Type' -e 'about (Vec X)'
  data [
  | nil. : Vec X 0
  | cons. (n : N) (𝑥 : X) (𝑦 : Vec X n) : Vec X (suc. n) ]
    : N → Type
  


A canonical type read back at a positive dimension shows that dimension as a superscript on its keyword.  The dimension shown is the *evaluation* dimension, the one it was degenerated by, so an undegenerated codatatype displays without a superscript even when it has a positive intrinsic (Gel) dimension.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def R : Type ≔ sig ( a : N )' -e 'def S : Type ≔ codata [ x .head : N ]' -e 'about N⁽ᵉ⁾' -e 'about R⁽ᵉ⁾' -e 'about S⁽ᵉᵉ⁾'
  data⁽ᵉ⁾ [
  | zero. : N⁽ᵉ⁾ 0 0
  | suc. : {𝑥₀ : N} {𝑥₁ : N} (𝑥₂ : N⁽ᵉ⁾ 𝑥₀ 𝑥₁) →⁽ᵉ⁾ N⁽ᵉ⁾ (suc. 𝑥₀) (suc. 𝑥₁) ]
    : Type⁽ᵉ⁾ N N
  
  sig⁽ᵉ⁾ (
    𝑥 .a : N⁽ᵉ⁾ (𝑥.0 .a) (𝑥.1 .a) )
    : Type⁽ᵉ⁾ R R
  
  codata⁽ᵉᵉ⁾ [
  | x .head : N⁽ᵉᵉ⁾ (x.02 .head) (x.12 .head) (x.20 .head) (x.21 .head) ]
    : Type⁽ᵉᵉ⁾ S⁽ᵉ⁾ S⁽ᵉ⁾ S⁽ᵉ⁾ S⁽ᵉ⁾
  



These superscripts are display-only: there is no way to write a degenerated canonical type directly, so the parser rejects a superscript on any of the three keywords.

  $ narya -e 'def N : Type ≔ data⁽ᵉ⁾ [ zero. ]'
   ￫ error[E0200]
   ￭ command-line exec string
   1 | def N : Type ≔ data⁽ᵉ⁾ [ zero. ]
     ^ parse error: invalid syntax
  
  [1]

  $ narya -e 'def R : Type ≔ sig⁽ᵉ⁾ ( a : Type )'
   ￫ error[E0200]
   ￭ command-line exec string
   1 | def R : Type ≔ sig⁽ᵉ⁾ ( a : Type )
     ^ parse error: invalid syntax
  
  [1]

  $ narya -e 'def S : Type ≔ codata⁽ᵉ⁾ [ x .head : Type ]'
   ￫ error[E0200]
   ￭ command-line exec string
   1 | def S : Type ≔ codata⁽ᵉ⁾ [ x .head : Type ]
     ^ parse error: invalid syntax
  
  [1]




A higher-dimensional (Gel-like) codatatype is read back at its intrinsic dimension.

  $ narya -dtt -e 'axiom A : Type' -e 'axiom Aʹ : A → Type' -e 'def Gel (A : Type) (Aʹ : A → Type) : Type⁽ᵈ⁾ A ≔ sig ( x .ungel : Aʹ x.0 )' -e 'about (Gel A Aʹ)'
  sig (
    x .ungel : Aʹ x.0 )
    : Type⁽ᵈ⁾ A
  



A permuted Gel-like codatatype is not a record type at all, since its fields can't be projected.  But it is the permutation of one, so it is read back by un-permuting it and applying the permutation to the result as a degeneracy.  Here it is uninstantiated, at permutations of two and of three dimensions.

  $ narya -parametric -e 'def Gel (A B : Type) (R : A → B → Type) : Id Type A B ≔ sig ( a .ungel : R a.0 a.1 )' -e 'axiom A : Type' -e 'axiom B : Type' -e 'axiom R : A → B → Type' -e 'about ((Gel A B R)⁽ᵉ¹⁾)' -e 'about ((Gel A B R)⁽ᵉᵉ¹⁾)'
  sym sig⁽ᵉ⁾ ( a .ungel : Id R a.02 a.12 (a.20 .ungel) (a.21 .ungel) )
    : Type⁽ᵉᵉ⁾ (Gel A B R) (Gel A B R) (Id A) (Id B)
  
  sig⁽ᵉᵉ⁾ (
    a .ungel : R⁽ᵉᵉ⁾ a.022 a.122 (a.202 .ungel) (a.212 .ungel) (a.220 .ungel)
                 (a.221 .ungel) )⁽²³¹⁾
    : Type⁽ᵉᵉᵉ⁾ (sym (Gel⁽ᵉ⁾ (Id A) (Id B) (Id R)))
        (sym (Gel⁽ᵉ⁾ (Id A) (Id B) (Id R)))
        (sym (Gel⁽ᵉ⁾ (Id A) (Id B) (Id R)))
        (sym (Gel⁽ᵉ⁾ (Id A) (Id B) (Id R))) A⁽ᵉᵉ⁾ B⁽ᵉᵉ⁾
  



An instantiated one is un-instantiated first, permuted as the uninstantiated codatatype it then is, and re-instantiated, like an instantiated datatype.  This is necessary even when it is *fully* instantiated, although such a one could be un-permuted where it stands by a symmetry of its instantiation arguments: the readback of a codatatype absorbs its instantiation arguments into the self variable, so it would then read as a record type of the lower dimension, which is not something the permutation could be applied to.

  $ narya -parametric -e 'def Gel (A B : Type) (R : A → B → Type) : Id Type A B ≔ sig ( a .ungel : R a.0 a.1 )' -e 'axiom A : Type' -e 'axiom B : Type' -e 'axiom R : A → B → Type' -e 'axiom a₀ : A' -e 'axiom a₁ : A' -e 'axiom a₂ : Id A a₀ a₁' -e 'axiom b₀ : B' -e 'axiom b₁ : B' -e 'axiom b₂ : Id B b₀ b₁' -e 'axiom r₀ : R a₀ b₀' -e 'axiom r₁ : R a₁ b₁' -e 'about ((Gel A B R)⁽ᵉ¹⁾ {a₀} {b₀} (r₀,) {a₁} {b₁} (r₁,) a₂ b₂)'
  sym sig⁽ᵉ⁾ ( a .ungel : Id R a.02 a.12 (a.20 .ungel) (a.21 .ungel) ) {a₀}
    {b₀} (_ ≔ r₀) {a₁} {b₁} (_ ≔ r₁) a₂ b₂
    : Type
  


A *partially* instantiated one is read back the same way, and there it is the only option: a permutation mixes its instantiated and uninstantiated dimensions, while an instantiation can only instantiate the last ones, so it has no un-permuted form where it stands.

  $ narya -parametric -e 'def Gel (A B : Type) (R : A → B → Type) : Id Type A B ≔ sig ( a .ungel : R a.0 a.1 )' -e 'axiom A : Type' -e 'axiom B : Type' -e 'axiom R : A → B → Type' -e 'axiom a₀ : A' -e 'axiom a₁ : A' -e 'axiom b₀ : B' -e 'axiom b₁ : B' -e 'axiom r₀ : R a₀ b₀' -e 'axiom r₁ : R a₁ b₁' -e 'about ((Gel A B R)⁽ᵉ¹⁾ {a₀} {b₀} (r₀,) {a₁} {b₁} (r₁,))'
  sym sig⁽ᵉ⁾ ( a .ungel : Id R a.02 a.12 (a.20 .ungel) (a.21 .ungel) ) {a₀}
    {b₀} (_ ≔ r₀) {a₁} {b₁} (_ ≔ r₁)
    : Type⁽ᵉ⁾ (Id A a₀ a₁) (Id B b₀ b₁)
  



Under glued evaluation, a definition that is an ordinary term rather than a case tree evaluates to a neutral whose value *realizes* that term.  Such a neutral has no potential value of its own, but the one it realizes to may, so we look there; thus a degeneracy of such a constant displays the same as the degeneracy of its definition.

  $ narya -parametric -e 'def Gel (A B : Type) (R : A → B → Type) : Id Type A B ≔ sig ( a .ungel : R a.0 a.1 )' -e 'axiom A : Type' -e 'axiom B : Type' -e 'axiom R : A → B → Type' -e 'axiom a₀ : A' -e 'axiom a₁ : A' -e 'axiom b₀ : B' -e 'axiom b₁ : B' -e 'axiom r₀ : R a₀ b₀' -e 'axiom r₁ : R a₁ b₁' -e 'def Z ≔ (Gel A B R)⁽ᵉ¹⁾ {a₀} {b₀} (r₀,) {a₁} {b₁} (r₁,)' -e 'about Z⁽ᵉ⁾'
  sig⁽ᵉᵉ⁾ (
    a .ungel : R⁽ᵉᵉ⁾ a.022 a.122 (a.202 .ungel) (a.212 .ungel) (a.220 .ungel)
                 (a.221 .ungel) )⁽²¹³⁾ {a₀} {a₀} {refl a₀} {b₀} {b₀}
    {refl b₀} {(_ ≔ r₀)} {(_ ≔ r₀)} (_ ≔ refl r₀) {a₁} {a₁} {refl a₁} {b₁}
    {b₁} {refl b₁} {(_ ≔ r₁)} {(_ ≔ r₁)} (_ ≔ refl r₁)
    : Type⁽ᵉᵉ⁾ (A⁽ᵉᵉ⁾ (refl a₀) (refl a₁)) (B⁽ᵉᵉ⁾ (refl b₀) (refl b₁))
        (sym (Gel⁽ᵉ⁾ (Id A) (Id B) (Id R)) {a₀} {b₀} (_ ≔ r₀) {a₁} {b₁}
           (_ ≔ r₁))
        (sym (Gel⁽ᵉ⁾ (Id A) (Id B) (Id R)) {a₀} {b₀} (_ ≔ r₀) {a₁} {b₁}
           (_ ≔ r₁))
  



The field-variable record syntax names the fields of the *whole* self-variable only.  A record whose field types project a proper face of a cube self-variable has no such display -- the projection would have to be written as a cube variable, "ungel.20", which is nonsense -- so it falls back to the self-variable syntax.

  $ narya -parametric -e 'def Gel (A B : Type) (R : A → B → Type) : Id Type A B ≔ sig ( a .ungel : R a.0 a.1 )' -e 'axiom A : Type' -e 'axiom B : Type' -e 'axiom R : A → B → Type' -e 'axiom a₀ : A' -e 'axiom a₁ : A' -e 'axiom a₂ : Id A a₀ a₁' -e 'axiom b₀ : B' -e 'axiom b₁ : B' -e 'axiom b₂ : Id B b₀ b₁' -e 'about (refl Gel (Id A) (Id B) (Id R) a₂ b₂)'
  sig⁽ᵉ⁾ (
    a .ungel : Id R a₂ b₂ (a.20 .ungel) (a.21 .ungel) )
    : Type⁽ᵉ⁾ (Gel A B R a₀ b₀) (Gel A B R a₁ b₁)
  



A degenerate codatatype or record is read back at its full dimension, showing the in-practice (higher-dimensional) field types, including higher-pi field types with their boundary faces.  It is *not* explicitly applied to any instantiation arguments, since those behave like (non-uniform) parameters rather than indices, appearing (through their fields, as instantiation arguments) in the types of the fields.

  $ narya -e 'axiom X : Type' -e 'def Stream : Type → Type ≔ A ↦ codata [ x .head : A | x .tail : Stream A ]' -e 'def R : Type ≔ sig ( a : Type, b : (a → Type) )' -e 'about (refl (Stream X))' -e 'about (refl R)' -e 'axiom x0 : Stream X' -e 'axiom x1 : Stream X' -e 'about (Id (Stream X) x0 x1)'
  codata⁽ᵉ⁾ [
  | x .head : Id X (x.0 .head) (x.1 .head)
  | x .tail : Stream⁽ᵉ⁾ (Id X) (x.0 .tail) (x.1 .tail) ]
    : Type⁽ᵉ⁾ (Stream X) (Stream X)
  
  sig⁽ᵉ⁾ (
    𝑥 .a : Type⁽ᵉ⁾ (𝑥.0 .a) (𝑥.1 .a),
    𝑥 .b : {𝑥₀ : 𝑥.0 .a} {𝑥₁ : 𝑥.1 .a} (𝑥₂ : 𝑥.2 .a 𝑥₀ 𝑥₁)
           →⁽ᵉ⁾ Type⁽ᵉ⁾ (𝑥.0 .b 𝑥₀) (𝑥.1 .b 𝑥₁) )
    : Type⁽ᵉ⁾ R R
  
  codata⁽ᵉ⁾ [
  | x .head : Id X (x0 .head) (x1 .head)
  | x .tail : Stream⁽ᵉ⁾ (Id X) (x0 .tail) (x1 .tail) ]
    : Type
  


For a codatatype with a higher field, every instance of that field that a comatch would have to provide is listed: one per partial bijection between the codatatype's dimension and the field's intrinsic dimension.  This includes the projectable instances (.1, .2) as well as the non-projectable "declaration" instance (.e) and intermediate forms, the latter computed in a context degenerated by the remaining dimensions.  In particular, the undegenerate type reproduces the field's declaration.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def √N : Type ≔ codata [ x .root.e : N ]' -e 'about √N' -e 'about (refl √N)' -e 'about (refl (refl √N))'
  codata [
  | x .root.e : N ]
    : Type
  
  codata⁽ᵉ⁾ [
  | x .root.e : N⁽ᵉ⁾ (x.02 .root) (x.12 .root)
  | x .root.1 : N ]
    : Type⁽ᵉ⁾ √N √N
  
  codata⁽ᵉᵉ⁾ [
  | x .root.e
    : N⁽ᵉᵉ⁾ (sym x.022 .root.1) (sym x.122 .root.1) (sym x.202 .root.1)
        (sym x.212 .root.1)
  | x .root.1 : N⁽ᵉ⁾ (x.20 .root) (x.21 .root)
  | x .root.2 : N⁽ᵉ⁾ (x.02 .root) (x.12 .root) ]
    : Type⁽ᵉᵉ⁾ √N⁽ᵉ⁾ √N⁽ᵉ⁾ √N⁽ᵉ⁾ √N⁽ᵉ⁾
  


A degenerate datatype is read back by evaluating each constructor's function-type in its higher-dimensional environment and instantiating the result at the eta-expanded lower-dimensional versions of the constructor itself.  This shows what the higher-dimensional constructor can actually be applied to and what its output is (so e.g. cons. lands in List⁽ᵉ⁾ (Id X) (cons. x₀ xs₀) (cons. x₁ xs₁)); a nullary constructor likewise displays its instantiated output, since the boundary of a higher-dimensional datatype behaves like indices.  This includes indexed datatypes, whose indices are degenerated as well (e.g. cons. lands in Vec⁽ᵉ⁾ (Id X) (suc. n₂) …).  Instantiation arguments are given as an application afterwards, just like indices are given for indexed datatypes.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'axiom X : Type' -e 'def List : Type → Type ≔ A ↦ data [ nil. | cons. (x : A) (xs : List A) ]' -e 'def Vec : Type → N → Type ≔ A ↦ data [ nil. : Vec A zero. | cons. : (n : N) → A → Vec A n → Vec A (suc. n) ]' -e 'about (refl (List X))' -e 'axiom x0 : List X' -e 'axiom x1 : List X' -e 'about (Id (List X) x0 x1)' -e 'about (refl N)' -e 'about (refl (Vec X zero.))' -e 'axiom v0 : Vec X 0' -e 'axiom v1 : Vec X 0' -e 'about Id (Vec X 0) v0 v1'
  data⁽ᵉ⁾ [
  | nil. : List⁽ᵉ⁾ (Id X) nil. nil.
  | cons.
    : {x₀ : X} {x₁ : X} (x₂ : Id X x₀ x₁) {xs₀ : List X} {xs₁ : List X}
      (xs₂ : List⁽ᵉ⁾ (Id X) xs₀ xs₁)
      →⁽ᵉ⁾ List⁽ᵉ⁾ (Id X) (cons. x₀ xs₀) (cons. x₁ xs₁) ]
    : Type⁽ᵉ⁾ (List X) (List X)
  
  data⁽ᵉ⁾ [
  | nil. : List⁽ᵉ⁾ (Id X) nil. nil.
  | cons.
    : {x₀ : X} {x₁ : X} (x₂ : Id X x₀ x₁) {xs₀ : List X} {xs₁ : List X}
      (xs₂ : List⁽ᵉ⁾ (Id X) xs₀ xs₁)
      →⁽ᵉ⁾ List⁽ᵉ⁾ (Id X) (cons. x₀ xs₀) (cons. x₁ xs₁) ] x0 x1
    : Type
  
  data⁽ᵉ⁾ [
  | zero. : N⁽ᵉ⁾ 0 0
  | suc. : {𝑥₀ : N} {𝑥₁ : N} (𝑥₂ : N⁽ᵉ⁾ 𝑥₀ 𝑥₁) →⁽ᵉ⁾ N⁽ᵉ⁾ (suc. 𝑥₀) (suc. 𝑥₁) ]
    : Type⁽ᵉ⁾ N N
  
  data⁽ᵉ⁾ [
  | nil. : Vec⁽ᵉ⁾ (Id X) {0} {0} (refl 0) nil. nil.
  | cons.
    : {n₀ : N} {n₁ : N} (n₂ : N⁽ᵉ⁾ n₀ n₁) {𝑥₀ : X} {𝑥₁ : X} (𝑥₂ : Id X 𝑥₀ 𝑥₁)
      {𝑦₀ : Vec X n₀} {𝑦₁ : Vec X n₁} (𝑦₂ : Vec⁽ᵉ⁾ (Id X) n₂ 𝑦₀ 𝑦₁)
      →⁽ᵉ⁾ Vec⁽ᵉ⁾ (Id X) {suc. n₀} {suc. n₁} (suc. n₂) (cons. n₀ 𝑥₀ 𝑦₀)
             (cons. n₁ 𝑥₁ 𝑦₁) ] {0} {0} (refl 0)
    : Type⁽ᵉ⁾ (Vec X 0) (Vec X 0)
  
  data⁽ᵉ⁾ [
  | nil. : Vec⁽ᵉ⁾ (Id X) {0} {0} (refl 0) nil. nil.
  | cons.
    : {n₀ : N} {n₁ : N} (n₂ : N⁽ᵉ⁾ n₀ n₁) {𝑥₀ : X} {𝑥₁ : X} (𝑥₂ : Id X 𝑥₀ 𝑥₁)
      {𝑦₀ : Vec X n₀} {𝑦₁ : Vec X n₁} (𝑦₂ : Vec⁽ᵉ⁾ (Id X) n₂ 𝑦₀ 𝑦₁)
      →⁽ᵉ⁾ Vec⁽ᵉ⁾ (Id X) {suc. n₀} {suc. n₁} (suc. n₂) (cons. n₀ 𝑥₀ 𝑦₀)
             (cons. n₁ 𝑥₁ 𝑦₁) ] {0} {0} (refl 0) v0 v1
    : Type
  


Since the boundary types come from the constructor's own environment (rather than by degenerating a single vertex), a degenerate datatype whose endpoints are *different* instances shows each boundary argument at its own correct type (x₀ : X but x₁ : Y, and xs₁ : List Y).

  $ narya -e 'axiom X : Type' -e 'axiom Y : Type' -e 'axiom A2 : Id Type X Y' -e 'def List : Type → Type ≔ A ↦ data [ nil. | cons. (x : A) (xs : List A) ]' -e 'about (refl List {X} {Y} A2)'
  data⁽ᵉ⁾ [
  | nil. : List⁽ᵉ⁾ A2 nil. nil.
  | cons.
    : {x₀ : X} {x₁ : Y} (x₂ : A2 x₀ x₁) {xs₀ : List X} {xs₁ : List Y}
      (xs₂ : List⁽ᵉ⁾ A2 xs₀ xs₁)
      →⁽ᵉ⁾ List⁽ᵉ⁾ A2 (cons. x₀ xs₀) (cons. x₁ xs₁) ]
    : Type⁽ᵉ⁾ (List X) (List Y)
  



In a parametricity configuration with no endpoints (arity 0), a degenerate datatype still displays: an arity-0 cube has no proper faces, so there is no boundary to instantiate at, but there is still the (empty) instantiation, displayed as ".".

  $ narya -arity 0 -parametric -e 'axiom X : Type' -e 'def List : Type → Type ≔ A ↦ data [ nil. | cons. (x : A) (xs : List A) ]' -e 'about (List X)⁽ᵉ⁾'
  data⁽ᵉ⁾ [
  | nil. : List⁽ᵉ⁾ (Id X) .
  | cons. : (x₀ : Id X .) (xs₀ : List⁽ᵉ⁾ (Id X) .) →⁽ᵉ⁾ List⁽ᵉ⁾ (Id X) . ]
    : Type⁽ᵉ⁾ .
  


A datatype defined nested inside a case tree is reached through the tree rather than as a top-level canonical type, so "about" displays the stored case tree.  Each nested datatype's constructor output types are shown faithfully (with the real datatype head) from the stored output term.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def W (n : N) : N → Type ≔ match n [ zero. ↦ data [ w0. : W n zero. ] | suc. m ↦ data [ w1. : W n (suc. m) ] ]' -e 'about W'
  n ↦
  match n [
  | suc. m ↦ data [
    | w1. : W n (suc. m) ]
  | zero. ↦ data [
    | w0. : W n 0 ]]
    : (n : N) → N → Type
  


A neutral whose value is a comatch (a coinductive record without eta) is read back and displayed as that comatch, by projecting each field.  This includes comatches that are only partially applied, and hence are not stored case trees that could be displayed by name, and degenerate (e.g. refl) comatches of a lower-field codatatype, whose fields are read back at the degenerated dimension.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Stream : Type → Type ≔ A ↦ codata [ x .head : A | x .tail : Stream A ]' -e 'def s : Stream N ≔ [ .head ↦ 0 | .tail ↦ s ]' -e 'def const : (A : Type) → A → Stream A ≔ A a ↦ [ .head ↦ a | .tail ↦ const A a ]' -e 'about s' -e 'about (const N 0)' -e 'about (refl s)'
  [ .head ↦ 0 | .tail ↦ s ]
    : Stream N
  
  [ .head ↦ 0 | .tail ↦ const N 0 ]
    : Stream N
  
  [ .head ↦ refl 0 | .tail ↦ refl s ]
    : Stream⁽ᵉ⁾ N⁽ᵉ⁾ s s
  



A comatch against a codatatype with a higher field is read back by reading back the value of each field instance, one per partial bijection between the comatch's dimension and the field's intrinsic dimension, exactly as the codatatype declaration lists them.  This includes a *degenerate* higher comatch such as "refl r", whose instances (.e and .1, as for the type "refl √N" above) are the corresponding degeneracies of the original body.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def √N : Type ≔ codata [ x .root.e : N ]' -e 'def r : √N ≔ [ .root.e ↦ 0 ]' -e 'about r' -e 'about (refl r)' -e 'about (refl (refl r))'
  [ .root.e ↦ 0 ]
    : √N
  
  [ .root.e ↦ refl 0 | .root.1 ↦ 0 ]
    : √N⁽ᵉ⁾ r r
  
  [ .root.e ↦ 0⁽ᵉᵉ⁾ | .root.1 ↦ refl 0 | .root.2 ↦ refl 0 ]
    : √N⁽ᵉᵉ⁾ (refl r) (refl r) (refl r) (refl r)
  



A comatch that is only partially applied, and hence has a non-empty closure environment, is read back the same way: the environment is transported into the degenerated context, so the body's variables are replaced by their values there.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def √N : Type ≔ codata [ x .root.e : N ]' -e 'def cst (a : N) : √N ≔ [ .root.e ↦ a.0 ]' -e 'about (cst 1)' -e 'about (refl (cst 1))'
  [ .root.e ↦ 1 ]
    : √N
  
  [ .root.e ↦ refl 1 | .root.1 ↦ 1 ]
    : √N⁽ᵉ⁾ (cst 1) (cst 1)
  



Each instance is read back in the context degenerated by its own remaining dimensions -- the same context the instance was checked in -- so inside a hole the body refers to the degenerated forms of the hole's variables (y.0 rather than y), and is a term that would actually typecheck there.

  $ narya -fake-interact 'def N : Type ≔ data [ zero. | suc. (_ : N) ] def √N : Type ≔ codata [ x .root.e : N ] def cst (a : N) : √N ≔ [ .root.e ↦ a.0 ] def foo (y : N) : N ≔ ? about in 0 (cst y) about in 0 (refl (cst y))'
   ￫ info[I0000]
   ￮ constant N defined
  
   ￫ info[I0000]
   ￮ constant √N defined
  
   ￫ info[I0000]
   ￮ constant cst defined
  
   ￫ info[I0000]
   ￮ constant foo defined, containing 1 hole
  
   ￫ info[I3003]
   ￮ hole ?0:
     
     y : N
     ----------------------------------------------------------------------
     N
  
   ￫ info[I3003]
   ￮ hole ?0:
     
     y : N
     ----------------------------------------------------------------------
     N
  
  [ .root.e ↦ y.0 ]
    : √N
  
   ￫ info[I3003]
   ￮ hole ?0:
     
     y : N
     ----------------------------------------------------------------------
     N
  
  [ .root.e ↦ refl y.0 | .root.1 ↦ y ]
    : √N⁽ᵉ⁾ (cst y) (cst y)
  



A comatch can mix lower and higher fields; all are read back, degenerate or not.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def C : Type ≔ codata [ x .head : N | x .root.e : N ]' -e 'def c : C ≔ [ .head ↦ 0 | .root.e ↦ suc. 0 ]' -e 'about c' -e 'about (refl c)'
  [ .head ↦ 0 | .root.e ↦ 1 ]
    : C
  
  [ .head ↦ refl 0 | .root.e ↦ refl 1 | .root.1 ↦ 1 ]
    : C⁽ᵉ⁾ c c
  



A struct at a codatatype with a nonzero intrinsic (Gel-like) dimension is read back too, rather than showing its application spine.

  $ narya -dtt -e 'axiom A : Type' -e 'axiom Aʹ : A → Type' -e 'def Gel (A : Type) (Aʹ : A → Type) : Type⁽ᵈ⁾ A ≔ sig ( x .ungel : Aʹ x.0 )' -e 'axiom a : A' -e 'axiom aʹ : Aʹ a' -e 'def h (x : A) (xʹ : Aʹ x) : Gel A Aʹ x ≔ (xʹ,)' -e 'about (h a aʹ)'
  (_ ≔ aʹ)
    : Gel A Aʹ a
  


In a parametricity configuration with no endpoints (arity 0), a degenerate higher comatch still lists the same instances as the corresponding degenerate codatatype.

  $ narya -arity 0 -parametric -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def √N : Type ≔ codata [ x .root.e : N ]' -e 'def r : √N ≔ [ .root.e ↦ 0 ]' -e 'about (√N⁽ᵉ⁾)' -e 'about (r⁽ᵉ⁾)'
  codata⁽ᵉ⁾ [
  | x .root.e : N⁽ᵉ⁾ .
  | x .root.1 : N ]
    : Type⁽ᵉ⁾ .
  
  [ .root.e ↦ refl 0 | .root.1 ↦ 0 ]
    : √N⁽ᵉ⁾ .
  


A comatch with an instance that is a genuinely stuck case tree, such as an unfilled hole, retains no trace of what it is stuck on once evaluated, so it isn't read back; the stored case tree is displayed instead, which does still name the hole.  A stuck instance of a comatch that has been applied, and so has no stored tree to fall back on, shows the application spine.

  $ narya -fake-interact 'def N : Type ≔ data [ zero. | suc. (_ : N) ] def √N : Type ≔ codata [ x .root.e : N ] def r : √N ≔ [ .root.e ↦ ? ] about r def cst (a : N) : √N ≔ [ .root.e ↦ ? ] about (cst 1)'
   ￫ info[I0000]
   ￮ constant N defined
  
   ￫ info[I0000]
   ￮ constant √N defined
  
   ￫ info[I0000]
   ￮ constant r defined, containing 1 hole
  
   ￫ info[I3003]
   ￮ hole ?0:
     
     ----------------------------------------------------------------------
     N
  
  [ .root.e ↦ ?0 ]
    : √N
  
   ￫ info[I0000]
   ￮ constant cst defined, containing 1 hole
  
   ￫ info[I3003]
   ￮ hole ?1:
     
     a.0 : N
     a.1 : N
     a.2 : N⁽ᵉ⁾ a.0 a.1
     ----------------------------------------------------------------------
     N
  
  [ .root.e ↦ ap cst {1} {1} (refl 1) .root ]
    : √N
  


The 'deg' of a comatch value is nontrivial when an already-evaluated value is acted on later by a degeneracy, as when it is looked up from an environment with a nontrivial degeneracy on the result.  Factoring an instance's partial bijection through that degeneracy can turn a shared dimension into a remaining one, so the instance's own remaining dimensions are fewer than those of the stored term it is built from; the extra ones are genuinely degenerate and are filled in as such, rather than the instance being dropped.

  $ narya -fake-interact 'def N : Type ≔ data [ zero. | suc. (_ : N) ] def √N : Type ≔ codata [ x .root.e : N ] def cst (a : N) : √N ≔ [ .root.e ↦ a.0 ] def f : √N ≔ let x ≔ cst 1 in ? about in 0 refl x'
   ￫ info[I0000]
   ￮ constant N defined
  
   ￫ info[I0000]
   ￮ constant √N defined
  
   ￫ info[I0000]
   ￮ constant cst defined
  
   ￫ info[I0000]
   ￮ constant f defined, containing 1 hole
  
   ￫ info[I3003]
   ￮ hole ?0:
     
     x ≔ cst 1 : √N
     ----------------------------------------------------------------------
     √N
  
   ￫ info[I3003]
   ￮ hole ?0:
     
     x ≔ cst 1 : √N
     ----------------------------------------------------------------------
     √N
  
  [ .root.e ↦ refl 1 | .root.1 ↦ 1 ]
    : √N⁽ᵉ⁾ (cst 1) (cst 1)
  


With a field of intrinsic dimension two, this happens even for an instance that still has remaining dimensions of its own (.root.e1 and .root.1e have one each, while the stored term has two).

  $ narya -fake-interact 'def N : Type ≔ data [ zero. | suc. (_ : N) ] def R2 : Type ≔ codata [ x .root.ee : N ] def cst2 (a : N) : R2 ≔ [ .root.ee ↦ a.00 ] def f : R2 ≔ let x ≔ cst2 1 in ? about in 0 refl x'
   ￫ info[I0000]
   ￮ constant N defined
  
   ￫ info[I0000]
   ￮ constant R2 defined
  
   ￫ info[I0000]
   ￮ constant cst2 defined
  
   ￫ info[I0000]
   ￮ constant f defined, containing 1 hole
  
   ￫ info[I3003]
   ￮ hole ?0:
     
     x ≔ cst2 1 : R2
     ----------------------------------------------------------------------
     R2
  
   ￫ info[I3003]
   ￮ hole ?0:
     
     x ≔ cst2 1 : R2
     ----------------------------------------------------------------------
     R2
  
  [ .root.ee ↦ refl 1 | .root.e1 ↦ 1 | .root.1e ↦ 1 ]
    : R2⁽ᵉ⁾ (cst2 1) (cst2 1)
  


A match that has not reduced is never reconstructed: wherever one occurs, it is displayed as the application spine of the neutral whose value it is, just as "echo" displays it.  So a function defined by matching shows its matches only as a bare constant, whose stored definition is displayed as written (as for "pred" above); applied to arguments, or degenerated, it shows as that application, inside any parameter abstractions that its definition has left to go.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def plus : N → N → N ≔ [ zero. ↦ m ↦ m | suc. n ↦ m ↦ suc. (plus n m) ]' -e 'axiom ax : N' -e 'about plus' -e 'about (plus ax)' -e 'about (plus 2)' -e 'about (refl plus)'
  𝑥 ↦ match 𝑥 [ suc. n ↦ m ↦ suc. (plus n m) | zero. ↦ m ↦ m ]
    : N → N → N
  
  plus ax
    : N → N
  
  m ↦ suc. (suc. m)
    : N → N
  
  𝑥 ⤇ ap plus 𝑥.2
    : {𝑥₀ : N} {𝑥₁ : N} (𝑥₂ : N⁽ᵉ⁾ 𝑥₀ 𝑥₁) {𝑦₀ : N} {𝑦₁ : N} (𝑦₂ : N⁽ᵉ⁾ 𝑦₀ 𝑦₁)
      →⁽ᵉ⁾ N⁽ᵉ⁾ (plus 𝑥₀ 𝑦₀) (plus 𝑥₁ 𝑦₁)
  

The boundary of a degenerate codatatype behaves like parameters, not like the indices that the boundary of a degenerate datatype behaves like: it is the *instantiated* form that one defines elements of by comatching.  So it is that form which displays as a codatatype, showing the types of the fields such a comatch must supply -- one instance of each higher field per partial bijection.  The uninstantiated form displays as a codatatype too, in terms of a self-variable cube whose faces the instantiation replaces.

  $ narya -e 'axiom A : Type' -e 'def √A : Type ≔ codata [ x .root.e : A ]' -e 'axiom s0 : √A' -e 'axiom s1 : √A' -e 'about √A' -e 'about √A⁽ᵉ⁾' -e 'about √A⁽ᵉ⁾ s0 s1'
  codata [
  | x .root.e : A ]
    : Type
  
  codata⁽ᵉ⁾ [
  | x .root.e : Id A (x.02 .root) (x.12 .root)
  | x .root.1 : A ]
    : Type⁽ᵉ⁾ √A √A
  
  codata⁽ᵉ⁾ [
  | x .root.e : Id A (refl s0 .root) (refl s1 .root)
  | x .root.1 : A ]
    : Type
  

The types displayed for the instantiated form are exactly the ones a comatch into it has to supply, as the holes show.

  $ narya -v -e 'axiom A : Type' -e 'def √A : Type ≔ codata [ x .root.e : A ]' -e 'axiom s0 : √A' -e 'axiom s1 : √A' -e 'def p : √A⁽ᵉ⁾ s0 s1 ≔ [ .root.e ↦ ? | .root.1 ↦ ? ]'
   ￫ info[I0001]
   ￮ axiom A assumed
  
   ￫ info[I0000]
   ￮ constant √A defined
  
   ￫ info[I0001]
   ￮ axiom s0 assumed
  
   ￫ info[I0001]
   ￮ axiom s1 assumed
  
   ￫ info[I0000]
   ￮ constant p defined, containing 2 holes
  
   ￫ info[I3003]
   ￮ hole ?0:
     
     ----------------------------------------------------------------------
     Id A (refl s0 .root) (refl s1 .root)
  
   ￫ info[I3003]
   ￮ hole ?1:
     
     ----------------------------------------------------------------------
     A
  
   ￫ error[E3002]
   ￮ command-line exec string contains open holes
  
  [1]

A record type has no higher fields, so its instantiation is displayed with a self variable of the lowered dimension, letting it come out in the field-variable syntax.

  $ narya -e 'axiom A : Type' -e 'def R : Type ≔ sig ( a : A, b : A )' -e 'axiom r0 : R' -e 'axiom r1 : R' -e 'about R⁽ᵉ⁾ r0 r1'
  sig⁽ᵉ⁾ (
    a : Id A (r0 .a) (r1 .a),
    b : Id A (r0 .b) (r1 .b) )
    : Type
  
