Fallbacks in the readback of a potential term

Reading back a potential term is display-only, and it is allowed to fail: when a piece of a case tree can't be displayed as the construct it came from, we show its application spine instead, which is always a correct thing to show and only a less informative one.  Most fallbacks say so as information, visible with -v (I0010); others are silent, because a spine is all there ever was to show.

This file records every remaining way that happens.  The first group has nothing to do with matches.  The second applies to matches of every kind.  The third is specific to an *implicit* match -- one with no stored motive, which recovers the types of its branches by refining the context rather than by applying a motive -- and does not arise for a match with an explicit motive or a non-dependent one.


I. Not about matches
====================

A case tree can get stuck with no record of what it got stuck on.  Evaluating a comatch keeps no trace of an unfilled hole in one of its instances, so once the comatch has been applied -- and hence is not a stored case tree that could be displayed by name -- that instance shows a spine.  The fallback is silent, since a stuck case tree that recorded nothing is indistinguishable from one that never had anything to record.

  $ narya -v -fake-interact 'def N : Type ≔ data [ zero. | suc. (_ : N) ] def √N : Type ≔ codata [ x .root.e : N ] def cst (a : N) : √N ≔ [ .root.e ↦ ? ] about (cst 1)'
   ￫ info[I0000]
   ￮ constant N defined
  
   ￫ info[I0000]
   ￮ constant √N defined
  
   ￫ info[I0000]
   ￮ constant cst defined, containing 1 hole
  
   ￫ info[I3003]
   ￮ hole ?0:
     
     a.0 : N
     a.1 : N
     a.2 : N⁽ᵉ⁾ a.0 a.1
     ----------------------------------------------------------------------
     N
  
  [ .root.e ↦ ap cst {1} {1} (refl 1) .root ]
    : √N
  

A case tree stuck on a metavariable rather than a match does record what it is stuck on, but there is nothing to display: a hole has no branches.

  $ narya -v -fake-interact 'def N : Type ≔ data [ zero. | suc. (_ : N) ] def f (n : N) : N ≔ ? about (f 0)'
   ￫ info[I0000]
   ￮ constant N defined
  
   ￫ info[I0000]
   ￮ constant f defined, containing 1 hole
  
   ￫ info[I3003]
   ￮ hole ?0:
     
     n : N
     ----------------------------------------------------------------------
     N
  
   ￫ info[I0010]
   ￮ not displaying a stuck metavariable; showing an application spine instead
  
  f 0
    : N
  

A neutral with no potential value at all -- an axiom, applied or not -- has nothing to read back, and "about" shows its normal form instead.  This too is silent.

  $ narya -v -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'axiom f : N → N' -e 'about (f 0)'
   ￫ info[I0000]
   ￮ constant N defined
  
   ￫ info[I0001]
   ￮ axiom f assumed
  
  f 0
    : N
  

Finally, a potential value that is a universe or a pi-type is shown as its spine, there being no declaration syntax for either.  That is the display one wants anyway, so this is not really a failure.

  $ narya -e 'def U : Type ≔ Type' -e 'about (U⁽ᵉ⁾)'
  Type⁽ᵉ⁾
    : Type⁽ᵉ⁾ Type Type
  


II. Matches of every kind
=========================

A branch that reaches a higher codata field cannot be displayed.  Raising the self into the context degenerated by a non-projectable instance's remaining dimensions reads it back and re-evaluates it, which it survives only if its spine really does evaluate to the comatch; in a branch of a match whose discriminee could not be refined the spine is still a stuck match, so projecting from it computes nothing.

This is worse for a match with an explicit motive than for an implicit one, because refinement is deliberately skipped when there is a motive to apply instead.  So an implicit match on a variable discriminee displays:

  $ narya -v -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def √N : Type ≔ codata [ x .root.e : N ]' -e 'about (let u : N → √N ≔ [ zero. ↦ [ .root.e ↦ zero. ] | suc. n ↦ [ .root.e ↦ suc. zero. ] ] in u)'
   ￫ info[I0000]
   ￮ constant N defined
  
   ￫ info[I0000]
   ￮ constant √N defined
  
  𝑥 ↦ match 𝑥 [ suc. n ↦ [ .root.e ↦ 1 ] | zero. ↦ [ .root.e ↦ 0 ] ]
    : N → √N
  

while the same match with a motive, on the same variable discriminee, does not:

  $ narya -v -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def √N : Type ≔ codata [ x .root.e : N ]' -e 'about (let u : N → √N ≔ n ↦ match n return _ ↦ √N [ zero. ↦ [ .root.e ↦ zero. ] | suc. k ↦ [ .root.e ↦ suc. zero. ] ] in u)'
   ￫ info[I0000]
   ￮ constant N defined
  
   ￫ info[I0000]
   ￮ constant √N defined
  
   ￫ info[I0010]
   ￮ not displaying a stuck match with a branch that reaches a higher field; showing an application spine instead
  
  n ↦ _let.F4.0.u{…} n
    : N → √N
  

and neither does an implicit one whose discriminee is not a variable, there being nothing to rebind:

  $ narya -v -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def √N : Type ≔ codata [ x .root.e : N ]' -e 'axiom ax : N' -e 'about (let u : N → √N ≔ [ zero. ↦ [ .root.e ↦ zero. ] | suc. n ↦ [ .root.e ↦ suc. zero. ] ] in u ax)'
   ￫ info[I0000]
   ￮ constant N defined
  
   ￫ info[I0000]
   ￮ constant √N defined
  
   ￫ info[I0001]
   ￮ axiom ax assumed
  
   ￫ info[I0010]
   ￮ not displaying a stuck match with a branch that reaches a higher field; showing an application spine instead
  
  _let.F5.0.u{…} ax
    : √N
  

A branch body that is itself an *anonymous* codatatype or record -- one written inline rather than named, so that it evaluates to a canonical value rather than to a neutral -- is displayed as a declaration rather than as a spine, which at a positive dimension means computing its field types.  A degenerate codatatype's field type is its declared type instantiated at that same field projected from the self variable at the proper faces of the self cube; and those faces are the boundary of the value, which we read off the instantiation arguments of its type and which is therefore only *definitionally* equal to it.  Here they are the match itself, which exposes no fields at all, so the projection fails and we fall back.

  $ narya -v -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Bool : Type ≔ data [ true. | false. ]' -e 'axiom b0 : Bool' -e 'axiom b1 : Bool' -e 'axiom b2 : Id Bool b0 b1' -e 'def F : Bool → Type ≔ [ true. ↦ codata [ x .head : N ] | false. ↦ N ]' -e 'about (refl F b2)'
   ￫ info[I0000]
   ￮ constant N defined
  
   ￫ info[I0000]
   ￮ constant Bool defined
  
   ￫ info[I0001]
   ￮ axiom b0 assumed
  
   ￫ info[I0001]
   ￮ axiom b1 assumed
  
   ￫ info[I0001]
   ￮ axiom b2 assumed
  
   ￫ info[I0000]
   ￮ constant F defined
  
   ￫ info[I0010]
   ￮ not displaying a stuck match with a branch body that is a codatatype whose fields cannot be projected at its boundary; showing an application spine instead
  
  Id F b2
    : Type⁽ᵉ⁾ (F b0) (F b1)
  

The same for a higher field, and for a record.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Bool : Type ≔ data [ true. | false. ]' -e 'axiom b0 : Bool' -e 'axiom b1 : Bool' -e 'axiom b2 : Id Bool b0 b1' -e 'def F : Bool → Type ≔ [ true. ↦ codata [ x .root.e : N ] | false. ↦ N ]' -e 'about (refl F b2)' -e 'def G : Bool → Type ≔ [ true. ↦ sig ( a : N ) | false. ↦ N ]' -e 'about (refl G b2)'
  Id F b2
    : Type⁽ᵉ⁾ (F b0) (F b1)
  
  Id G b2
    : Type⁽ᵉ⁾ (G b0) (G b1)
  

Only a projection fails, so a codatatype with no fields to project displays, boundary or no boundary.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Bool : Type ≔ data [ true. | false. ]' -e 'axiom b0 : Bool' -e 'axiom b1 : Bool' -e 'axiom b2 : Id Bool b0 b1' -e 'def F : Bool → Type ≔ [ true. ↦ codata [ ] | false. ↦ N ]' -e 'about (refl F b2)'
  match b2 [ false. ⤇ N⁽ᵉ⁾ | true. ⤇ codata⁽ᵉ⁾ [ ] ]
    : Type⁽ᵉ⁾ (F b0) (F b1)
  

So does an anonymous *datatype*: readback of a degenerate datatype evaluates each constructor's function-type in a faced environment instead of projecting from boundary self variables, so it never needs the boundary to be a datatype at all.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Bool : Type ≔ data [ true. | false. ]' -e 'axiom b0 : Bool' -e 'axiom b1 : Bool' -e 'axiom b2 : Id Bool b0 b1' -e 'def F : Bool → Type ≔ [ true. ↦ data [ u. | v. ] | false. ↦ N ]' -e 'about (refl F b2)'
  match b2 [
  | false. ⤇ N⁽ᵉ⁾
  | true. ⤇ data⁽ᵉ⁾ [
    | u. : F⁽ᵉ⁾ {true.} {true.} true. u. u.
    | v. : F⁽ᵉ⁾ {true.} {true.} true. v. v. ]]
    : Type⁽ᵉ⁾ (F b0) (F b1)
  

And at dimension zero there is no boundary to instantiate at, so the same codatatype displays.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Bool : Type ≔ data [ true. | false. ]' -e 'axiom b : Bool' -e 'def F : Bool → Type ≔ [ true. ↦ codata [ x .head : N ] | false. ↦ N ]' -e 'about (F b)'
  match b [ false. ↦ N | true. ↦ codata [ x .head : N ] ]
    : Type
  

Note that this cannot be ruled out in advance by asking whether every face of the self cube is a codatatype.  An intrinsically higher, Gel-like codatatype has for its boundary the endpoint types of the path that it is, which are arbitrary types that its field types take as arguments rather than project from.

  $ narya -parametric -e 'def Gel (A B : Type) (R : A → B → Type) : Id Type A B ≔ sig ( a .ungel : R a.0 a.1 )' -e 'axiom A : Type' -e 'axiom B : Type' -e 'axiom R : A → B → Type' -e 'about (Gel A B R)'
  sig (
    a .ungel : R a.0 a.1 )
    : Type⁽ᵉ⁾ A B
  

In a degenerated environment, the type at which a branch body is read back is the motive instantiated at the boundary of that body, which we get by evaluating it in the faces of its own environment.  A branch body is a case tree, so its value at a face may be a case tree too, and then there is nothing to instantiate at.  Here the bodies are lambdas, so they are.

  $ narya -v -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Bool : Type ≔ data [ true. | false. ]' -e 'axiom b0 : Bool' -e 'axiom b1 : Bool' -e 'axiom b2 : Id Bool b0 b1' -e 'axiom ax : N' -e 'def g : Bool → (N → N) ≔ b ↦ match b return _ ↦ N → N [ true. ↦ n ↦ n | false. ↦ n ↦ zero. ]' -e 'about (refl g b2 (refl ax))'
   ￫ info[I0000]
   ￮ constant N defined
  
   ￫ info[I0000]
   ￮ constant Bool defined
  
   ￫ info[I0001]
   ￮ axiom b0 assumed
  
   ￫ info[I0001]
   ￮ axiom b1 assumed
  
   ￫ info[I0001]
   ￮ axiom b2 assumed
  
   ￫ info[I0001]
   ￮ axiom ax assumed
  
   ￫ info[I0000]
   ￮ constant g defined
  
   ￫ info[I0010]
   ￮ not displaying a stuck match with a branch body that is a case tree at one of its boundary faces; showing an application spine instead
  
  ap g b2 (refl ax)
    : N⁽ᵉ⁾ (g b0 ax) (g b1 ax)
  

Branch bodies that are neutral rather than case trees have kinetic values at their faces, and the same match displays.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Bool : Type ≔ data [ true. | false. ]' -e 'axiom b0 : Bool' -e 'axiom b1 : Bool' -e 'axiom b2 : Id Bool b0 b1' -e 'axiom ax : N' -e 'def idn : N → N ≔ n ↦ n' -e 'def zer : N → N ≔ n ↦ zero.' -e 'def g : Bool → (N → N) ≔ b ↦ match b return _ ↦ N → N [ true. ↦ idn | false. ↦ zer ]' -e 'about (refl g b2 (refl ax))'
  match b2
  return 𝑥 𝑦 𝑧 ↦
         {𝑥₀ : N} {𝑥₁ : N} (𝑥₂ : N⁽ᵉ⁾ 𝑥₀ 𝑥₁)
         →⁽ᵉ⁾ N⁽ᵉ⁾
                ((match 𝑥 return 𝑤 ↦ N → N [ false. ↦ zer | true. ↦ idn ]) 𝑥₀)
                ((match 𝑦 return 𝑤 ↦ N → N [ false. ↦ zer | true. ↦ idn ]) 𝑥₁) [
  | false. ⤇ ap zer
  | true. ⤇ ap idn] (refl ax)
    : N⁽ᵉ⁾ (g b0 ax) (g b1 ax)
  

This is now the only match-specific failure that an explicit motive or a non-dependent match can suffer besides a higher field, since it is exactly the case in which the motive is what computes the branch types.  With no motive we read the branches back at the type of the match itself and never instantiate a family at their boundaries.


III. Implicit matches only
==========================

An implicit match stores no motive, so the only way to get the type at which a branch body was checked is to refine: rebind the discriminee, and the datatype's index and boundary variables, to the values this branch's constructor gives them.  When that fails the body is read back at the *unrefined* type of the match, which is definitionally equal to the refined one but need not expose the canonical form the body has.  Then readback raises and we fall back.

Refinement can fail because the discriminee, an index, or a boundary variable is not a free variable, carries a degeneracy, is keyed, or is a duplicate; because no consistent permutation of the context rebinds them; because rebinding kills the self that a comatch in the body would be read back against; or because the branch body does not survive the eval-readback cycle that refining its *value* puts it through (see IV).  None of these is reported on its own -- each just means we read the branch back unrefined -- so what one sees is the failure that follows, if any.

Here the discriminee is an axiom rather than a variable, so nothing rebinds, and the branch bodies do not synthesize at the unrefined type "T x", which is itself a stuck match rather than the pi-type and datatype that the bodies need.

  $ narya -v -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Bool : Type ≔ data [ true. | false. ]' -e 'def T : Bool → Type ≔ [ true. ↦ N → N | false. ↦ N ]' -e 'axiom b : Bool' -e 'about (let f : (x : Bool) → T x ≔ [ true. ↦ n ↦ n | false. ↦ zero. ] in f b)'
   ￫ info[I0000]
   ￮ constant N defined
  
   ￫ info[I0000]
   ￮ constant Bool defined
  
   ￫ info[I0000]
   ￮ constant T defined
  
   ￫ info[I0001]
   ￮ axiom b assumed
  
   ￫ info[I0010]
   ￮ not displaying a stuck match with a branch body that is a constructor, which does not synthesize; showing an application spine instead
  
  _let.F6.0.f{…} b
    : T b
  

The same match with an explicit motive displays, since the motive computes each branch's type without refining anything.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Bool : Type ≔ data [ true. | false. ]' -e 'def T : Bool → Type ≔ [ true. ↦ N → N | false. ↦ N ]' -e 'axiom b : Bool' -e 'about (let f : (x : Bool) → T x ≔ x ↦ match x return y ↦ T y [ true. ↦ n ↦ n | false. ↦ zero. ] in f b)'
  match b
  return y ↦ T y [ false. ↦ 0 | true. ↦ n ↦ n ]
    : T b
  

Reading a branch back at an unrefined type can also fail inside a constructor, when the type is a degenerate datatype whose instantiation arguments are not the corresponding constructors.  This is the implicit version of the degenerated-environment example above: with no motive there is no boundary of the body to fail on, but the unrefined type fails instead.

  $ narya -v -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Bool : Type ≔ data [ true. | false. ]' -e 'axiom b0 : Bool' -e 'axiom b1 : Bool' -e 'axiom b2 : Id Bool b0 b1' -e 'axiom ax : N' -e 'def g : Bool → (N → N) ≔ [ true. ↦ n ↦ n | false. ↦ n ↦ zero. ]' -e 'about (refl g b2 (refl ax))'
   ￫ info[I0000]
   ￮ constant N defined
  
   ￫ info[I0000]
   ￮ constant Bool defined
  
   ￫ info[I0001]
   ￮ axiom b0 assumed
  
   ￫ info[I0001]
   ￮ axiom b1 assumed
  
   ￫ info[I0001]
   ￮ axiom b2 assumed
  
   ￫ info[I0001]
   ￮ axiom ax assumed
  
   ￫ info[I0000]
   ￮ constant g defined
  
   ￫ info[I0010]
   ￮ not displaying a stuck match with a branch body that is a constructor whose instantiation argument is not a constructor; showing an application spine instead
  
  ap g b2 (refl ax)
    : N⁽ᵉ⁾ (g b0 ax) (g b1 ax)
  


IV. Degradations that are not fallbacks
=======================================

A match in a degenerated environment displays without a "return" clause, rather than not at all, when its motive can't be read back as a family of the total dimension: when the type of the match is not a fully instantiated neutral whose instantiation covers the dimensions the environment adds, or when a match at one of those faces can't be displayed.  Here the discriminee is a path between two constructors, so the match at each endpoint reduces to a branch body and there is none to show.

  $ narya -v -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Bool : Type ≔ data [ true. | false. ]' -e 'def T : Bool → Type ≔ [ true. ↦ N | false. ↦ Bool ]' -e 'def g : (b : Bool) → T b ≔ b ↦ match b return x ↦ T x [ true. ↦ zero. | false. ↦ true. ]' -e 'axiom p : Id Bool true. false.' -e 'about (refl g p)'
   ￫ info[I0000]
   ￮ constant N defined
  
   ￫ info[I0000]
   ￮ constant Bool defined
  
   ￫ info[I0000]
   ￮ constant T defined
  
   ￫ info[I0000]
   ￮ constant g defined
  
   ￫ info[I0001]
   ￮ axiom p assumed
  
  match p [ false. ⤇ true. | true. ⤇ refl 0 ]
    : Id T p 0 true.
  

Refining a branch refines its *value* as well as its type, by reading the body back at the refined type in the old context and re-evaluating it in the new one.  A body that reads back as a display-only term does not survive that cycle: an anonymous canonical type in a branch reads back as a declaration, which readback marks unevaluable -- a codatatype or record by carrying no fibrancy, a datatype by the potential instantiation wrapped around it -- and evaluating one raises.  We catch that and read the branch back unrefined, which displays but shows the discriminee where the constructor would be.

Note that these have to be reached through readback: "about" on a zero-dimensional constant with a stored definition unparses that definition directly, without reading anything back, so a bare constant will not exercise this.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Bool : Type ≔ data [ true. | false. ]' -e 'about (let F : Bool → Type ≔ b ↦ match b [ true. ↦ Id Bool b b | false. ↦ N ] in F)'
  b ↦ match b [ false. ↦ N | true. ↦ Bool⁽ᵉ⁾ true. true. ]
    : Bool → Type
  

An anonymous record in the same position keeps the unrefined "b" instead.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'def Bool : Type ≔ data [ true. | false. ]' -e 'about (let F : Bool → Type ≔ b ↦ match b [ true. ↦ sig ( a : Id Bool b b ) | false. ↦ N ] in F)'
  b ↦ match b [ false. ↦ N | true. ↦ sig ( a : Bool⁽ᵉ⁾ b b ) ]
    : Bool → Type
  

A non-dependent match records one type, which is that of the match and of every branch alike, and never displays a motive: there is no surface syntax for such a match other than the placeholder "return _ … _ ↦ _", which says nothing about the type.  Such a match arises when the discriminee is not a variable to refine and the user gives no motive, and the stored type is what lets its branches be read back when it is eliminated further.

  $ narya -e 'def N : Type ≔ data [ zero. | suc. (_ : N) ]' -e 'axiom ax : N' -e 'axiom bx : N' -e 'about (let h : N → N ≔ match ax [ zero. ↦ n ↦ n | suc. k ↦ n ↦ zero. ] in h bx)'
  match ax [ suc. k ↦ n ↦ 0 | zero. ↦ n ↦ n ] bx
    : N
  
