open Testutil

(* Exercise the unparsing of canonical types (records, datatypes, codatatypes), matches, and comatches by defining constants with such case trees and checking that they unparse back to the expected surface syntax.  The autogenerated variable names (𝑥, 𝑦, …) are those produced for nameless bound variables. *)

let check name ty tm expected =
  let actual = Repl.unparse_def name ty tm in
  if actual <> expected then
    raise (Failure (Printf.sprintf "unparse %s:\n  expected: %s\n  actual:   %s" name expected actual))

let () =
  Repl.run @@ fun () ->
  (* Record type, with a dependent field. *)
  check "R" "Type" "sig ( a : Type, b : (a → Type) )"
    "sig (\n  a : Type,\n  b : a → Type )";
  (* Empty record. *)
  check "Unit" "Type" "sig ()" "sig ()";
  (* Datatype with a recursive constructor argument. *)
  check "Nat" "Type" "data [ zero. | suc. (_ : Nat) ]" "data [\n| zero.\n| suc. (𝑥 : Nat) ]";
  (* Empty datatype. *)
  check "Empty" "Type" "data [ ]" "data []";
  (* Codatatype. *)
  check "Stream" "Type" "codata [ x .head : Type | x .tail : Type ]"
    "codata [\n| 𝑥 .head : Type\n| 𝑥 .tail : Type ]";
  (* Codatatype with a higher field, whose declaration type is degenerated by the field's dimension. *)
  check "HStream" "Type" "codata [ x .f.e : Type → Type | x .g : Type ]"
    "codata [\n| 𝑥 .f.e : Type → Type\n| 𝑥 .g : Type ]";
  (* A match (pattern-matching lambda).  Branches come out in constructor-name order. *)
  check "pred" "Nat → Nat" "[ zero. ↦ zero. | suc. n ↦ n ]"
    "𝑥 ↦ match 𝑥 [ suc. n ↦ n | zero. ↦ 0 ]";
  (* A comatch. *)
  check "consts" "Stream" "[ .head ↦ Nat | .tail ↦ Empty ]" "[ .head ↦ Nat | .tail ↦ Empty ]";
  ()
