name: "Build"

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - run: nix profile install nixpkgs#cachix
    - run: cachix watch-exec narya -- nix build --accept-flake-config .
    - run: cachix watch-exec narya -- nix develop
